// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^.*Battery: -?\d*%, .*charging \(-?\d*% [^ ]* \d*:\d*:\d*\), \d*:\d*:\d* .*$`

package matchers

import "unicode/utf8"

// MatchApm reports whether input fully matches the regex `^.*Battery: -?\d*%, .*charging \(-?\d*% [^ ]* \d*:\d*:\d*\), \d*:\d*:\d* .*$`.
func MatchApm(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '`':
				state = 1
			case r == 'a':
				state = 3
			case r >= 'b' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= 's':
				state = 1
			case r == 't':
				state = 4
			case r >= 'u' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= 's':
				state = 1
			case r == 't':
				state = 5
			case r >= 'u' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= 'd':
				state = 1
			case r == 'e':
				state = 6
			case r >= 'f' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= 'q':
				state = 1
			case r == 'r':
				state = 7
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= 'x':
				state = 1
			case r == 'y':
				state = 8
			case r >= 'z' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '9':
				state = 1
			case r == ':':
				state = 9
			case r >= ';' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 10
			case r >= '!' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '$':
				state = 1
			case r == '%':
				state = 11
			case r >= '&' && r <= ',':
				state = 1
			case r == '-':
				state = 12
			case r >= '.' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 12
			case r >= ':' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '+':
				state = 1
			case r == ',':
				state = 13
			case r >= '-' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 12:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '$':
				state = 1
			case r == '%':
				state = 11
			case r >= '&' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 12
			case r >= ':' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 14
			case r >= '!' && r <= 'A':
				state = 1
			case r == 'B':
				state = 2
			case r >= 'C' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= '`':
				state = 14
			case r == 'a':
				state = 17
			case r == 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'g':
				state = 14
			case r == 'h':
				state = 18
			case r >= 'i' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 's':
				state = 14
			case r == 't':
				state = 19
			case r >= 'u' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= '`':
				state = 14
			case r == 'a':
				state = 20
			case r == 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 's':
				state = 14
			case r == 't':
				state = 21
			case r >= 'u' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'q':
				state = 14
			case r == 'r':
				state = 22
			case r >= 's' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r == 'd':
				state = 14
			case r == 'e':
				state = 23
			case r >= 'f' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 22:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'f':
				state = 14
			case r == 'g':
				state = 24
			case r >= 'h' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 23:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'q':
				state = 14
			case r == 'r':
				state = 25
			case r >= 's' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'h':
				state = 14
			case r == 'i':
				state = 26
			case r >= 'j' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 25:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'x':
				state = 14
			case r == 'y':
				state = 27
			case r >= 'z' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'm':
				state = 14
			case r == 'n':
				state = 28
			case r >= 'o' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 27:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '9':
				state = 14
			case r == ':':
				state = 29
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= 'f':
				state = 14
			case r == 'g':
				state = 30
			case r >= 'h' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 29:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\x1f':
				state = 14
			case r == ' ':
				state = 31
			case r >= '!' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\x1f':
				state = 14
			case r == ' ':
				state = 32
			case r >= '!' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '$':
				state = 14
			case r == '%':
				state = 33
			case r >= '&' && r <= ',':
				state = 14
			case r == '-':
				state = 34
			case r >= '.' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 34
			case r >= ':' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\'':
				state = 14
			case r == '(':
				state = 35
			case r >= ')' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 33:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '+':
				state = 14
			case r == ',':
				state = 36
			case r >= '-' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 34:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '$':
				state = 14
			case r == '%':
				state = 33
			case r >= '&' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 34
			case r >= ':' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 35:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '$':
				state = 14
			case r == '%':
				state = 37
			case r >= '&' && r <= ',':
				state = 14
			case r == '-':
				state = 38
			case r >= '.' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 38
			case r >= ':' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 36:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\x1f':
				state = 14
			case r == ' ':
				state = 14
			case r >= '!' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 37:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\x1f':
				state = 14
			case r == ' ':
				state = 39
			case r >= '!' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 38:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '$':
				state = 14
			case r == '%':
				state = 37
			case r >= '&' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 38
			case r >= ':' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 39:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 40:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 40
			case r == ' ':
				state = 44
			case r >= '!' && r <= '\U0010ffff':
				state = 40
			default:
				return false
			}
		case 41:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 41
			case r == ':':
				state = 45
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 42:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= '`':
				state = 39
			case r == 'a':
				state = 46
			case r == 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 43:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'g':
				state = 39
			case r == 'h':
				state = 47
			case r >= 'i' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 44:
			switch {
			case r >= '0' && r <= '9':
				state = 44
			case r == ':':
				state = 48
			default:
				return false
			}
		case 45:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 45
			case r == ':':
				state = 49
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 46:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 's':
				state = 39
			case r == 't':
				state = 50
			case r >= 'u' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 47:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= '`':
				state = 39
			case r == 'a':
				state = 51
			case r == 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 48:
			switch {
			case r >= '0' && r <= '9':
				state = 48
			case r == ':':
				state = 52
			default:
				return false
			}
		case 49:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '(':
				state = 14
			case r == ')':
				state = 53
			case r >= '*' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 49
			case r >= ':' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 50:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 's':
				state = 39
			case r == 't':
				state = 54
			case r >= 'u' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 51:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'q':
				state = 39
			case r == 'r':
				state = 55
			case r >= 's' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 52:
			switch {
			case r == ')':
				state = 56
			case r >= '0' && r <= '9':
				state = 52
			default:
				return false
			}
		case 53:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '+':
				state = 14
			case r == ',':
				state = 57
			case r >= '-' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 54:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r == 'd':
				state = 39
			case r == 'e':
				state = 58
			case r >= 'f' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 55:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'f':
				state = 39
			case r == 'g':
				state = 59
			case r >= 'h' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 56:
			switch {
			case r == ',':
				state = 60
			default:
				return false
			}
		case 57:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\x1f':
				state = 14
			case r == ' ':
				state = 61
			case r >= '!' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 58:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'q':
				state = 39
			case r == 'r':
				state = 62
			case r >= 's' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 59:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'h':
				state = 39
			case r == 'i':
				state = 63
			case r >= 'j' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 60:
			switch {
			case r == ' ':
				state = 64
			default:
				return false
			}
		case 61:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 61
			case r == ':':
				state = 65
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 62:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'x':
				state = 39
			case r == 'y':
				state = 66
			case r >= 'z' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 63:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'm':
				state = 39
			case r == 'n':
				state = 67
			case r >= 'o' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 64:
			switch {
			case r >= '0' && r <= '9':
				state = 64
			case r == ':':
				state = 68
			default:
				return false
			}
		case 65:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 65
			case r == ':':
				state = 69
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 66:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= '9':
				state = 39
			case r == ':':
				state = 70
			case r >= ';' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 67:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 41
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= 'f':
				state = 39
			case r == 'g':
				state = 71
			case r >= 'h' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 68:
			switch {
			case r >= '0' && r <= '9':
				state = 68
			case r == ':':
				state = 72
			default:
				return false
			}
		case 69:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\x1f':
				state = 14
			case r == ' ':
				state = 73
			case r >= '!' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 69
			case r >= ':' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 70:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 74
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 71:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 39
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 75
			case r >= '!' && r <= 'A':
				state = 39
			case r == 'B':
				state = 42
			case r >= 'C' && r <= 'b':
				state = 39
			case r == 'c':
				state = 43
			case r >= 'd' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 72:
			switch {
			case r == ' ':
				state = 76
			case r >= '0' && r <= '9':
				state = 72
			default:
				return false
			}
		case 73:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 74:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '$':
				state = 14
			case r == '%':
				state = 33
			case r >= '&' && r <= ',':
				state = 14
			case r == '-':
				state = 34
			case r >= '.' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 79
			case r == ':':
				state = 45
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 75:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '\'':
				state = 14
			case r == '(':
				state = 35
			case r >= ')' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 41
			case r == ':':
				state = 45
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 76:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 76
			case r >= '\v' && r <= '\U0010ffff':
				state = 76
			default:
				return false
			}
		case 77:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= '`':
				state = 73
			case r == 'a':
				state = 80
			case r == 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 78:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'g':
				state = 73
			case r == 'h':
				state = 81
			case r >= 'i' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 79:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r >= '\v' && r <= '$':
				state = 14
			case r == '%':
				state = 33
			case r >= '&' && r <= '/':
				state = 14
			case r >= '0' && r <= '9':
				state = 79
			case r == ':':
				state = 45
			case r >= ';' && r <= 'A':
				state = 14
			case r == 'B':
				state = 15
			case r >= 'C' && r <= 'b':
				state = 14
			case r == 'c':
				state = 16
			case r >= 'd' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 80:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 's':
				state = 73
			case r == 't':
				state = 82
			case r >= 'u' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 81:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= '`':
				state = 73
			case r == 'a':
				state = 83
			case r == 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 82:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 's':
				state = 73
			case r == 't':
				state = 84
			case r >= 'u' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 83:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'q':
				state = 73
			case r == 'r':
				state = 85
			case r >= 's' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 84:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r == 'd':
				state = 73
			case r == 'e':
				state = 86
			case r >= 'f' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 85:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'f':
				state = 73
			case r == 'g':
				state = 87
			case r >= 'h' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 86:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'q':
				state = 73
			case r == 'r':
				state = 88
			case r >= 's' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 87:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'h':
				state = 73
			case r == 'i':
				state = 89
			case r >= 'j' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 88:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'x':
				state = 73
			case r == 'y':
				state = 90
			case r >= 'z' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 89:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'm':
				state = 73
			case r == 'n':
				state = 91
			case r >= 'o' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 90:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '9':
				state = 73
			case r == ':':
				state = 92
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 91:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= 'f':
				state = 73
			case r == 'g':
				state = 93
			case r >= 'h' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 92:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\x1f':
				state = 73
			case r == ' ':
				state = 94
			case r >= '!' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 93:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\x1f':
				state = 73
			case r == ' ':
				state = 95
			case r >= '!' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 94:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '$':
				state = 73
			case r == '%':
				state = 96
			case r >= '&' && r <= ',':
				state = 73
			case r == '-':
				state = 97
			case r >= '.' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 97
			case r >= ':' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 95:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\'':
				state = 73
			case r == '(':
				state = 98
			case r >= ')' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 96:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '+':
				state = 73
			case r == ',':
				state = 99
			case r >= '-' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 97:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '$':
				state = 73
			case r == '%':
				state = 96
			case r >= '&' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 97
			case r >= ':' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 98:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '$':
				state = 73
			case r == '%':
				state = 100
			case r >= '&' && r <= ',':
				state = 73
			case r == '-':
				state = 101
			case r >= '.' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 101
			case r >= ':' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 99:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\x1f':
				state = 73
			case r == ' ':
				state = 73
			case r >= '!' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 100:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\x1f':
				state = 73
			case r == ' ':
				state = 102
			case r >= '!' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 101:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '$':
				state = 73
			case r == '%':
				state = 100
			case r >= '&' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 101
			case r >= ':' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 102:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 103:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 103
			case r == ':':
				state = 106
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 104:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= '`':
				state = 102
			case r == 'a':
				state = 107
			case r == 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 105:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'g':
				state = 102
			case r == 'h':
				state = 108
			case r >= 'i' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 106:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 106
			case r == ':':
				state = 109
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 107:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 's':
				state = 102
			case r == 't':
				state = 110
			case r >= 'u' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 108:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= '`':
				state = 102
			case r == 'a':
				state = 111
			case r == 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 109:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '(':
				state = 73
			case r == ')':
				state = 112
			case r >= '*' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 109
			case r >= ':' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 110:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 's':
				state = 102
			case r == 't':
				state = 113
			case r >= 'u' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 111:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'q':
				state = 102
			case r == 'r':
				state = 114
			case r >= 's' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 112:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '+':
				state = 73
			case r == ',':
				state = 115
			case r >= '-' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 113:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r == 'd':
				state = 102
			case r == 'e':
				state = 116
			case r >= 'f' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 114:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'f':
				state = 102
			case r == 'g':
				state = 117
			case r >= 'h' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 115:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\x1f':
				state = 73
			case r == ' ':
				state = 118
			case r >= '!' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 116:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'q':
				state = 102
			case r == 'r':
				state = 119
			case r >= 's' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 117:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'h':
				state = 102
			case r == 'i':
				state = 120
			case r >= 'j' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 118:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 118
			case r == ':':
				state = 121
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 119:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'x':
				state = 102
			case r == 'y':
				state = 122
			case r >= 'z' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 120:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'm':
				state = 102
			case r == 'n':
				state = 123
			case r >= 'o' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 121:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 121
			case r == ':':
				state = 124
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 122:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= '9':
				state = 102
			case r == ':':
				state = 125
			case r >= ';' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 123:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 103
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= 'f':
				state = 102
			case r == 'g':
				state = 126
			case r >= 'h' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 124:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\x1f':
				state = 73
			case r == ' ':
				state = 73
			case r >= '!' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 124
			case r >= ':' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 125:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 127
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 126:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 102
			case r == '\n':
				state = 40
			case r >= '\v' && r <= '\x1f':
				state = 102
			case r == ' ':
				state = 128
			case r >= '!' && r <= 'A':
				state = 102
			case r == 'B':
				state = 104
			case r >= 'C' && r <= 'b':
				state = 102
			case r == 'c':
				state = 105
			case r >= 'd' && r <= '\U0010ffff':
				state = 102
			default:
				return false
			}
		case 127:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '$':
				state = 73
			case r == '%':
				state = 96
			case r >= '&' && r <= ',':
				state = 73
			case r == '-':
				state = 97
			case r >= '.' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 129
			case r == ':':
				state = 106
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 128:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '\'':
				state = 73
			case r == '(':
				state = 98
			case r >= ')' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 103
			case r == ':':
				state = 106
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		case 129:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 73
			case r >= '\v' && r <= '$':
				state = 73
			case r == '%':
				state = 96
			case r >= '&' && r <= '/':
				state = 73
			case r >= '0' && r <= '9':
				state = 129
			case r == ':':
				state = 106
			case r >= ';' && r <= 'A':
				state = 73
			case r == 'B':
				state = 77
			case r >= 'C' && r <= 'b':
				state = 73
			case r == 'c':
				state = 78
			case r >= 'd' && r <= '\U0010ffff':
				state = 73
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 73, 76, 77, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129:
		return true
	default:
		return false
	}
}
