// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^distccd\[\d+\] (\([^\)]+\))? ?.*$`

package matchers

import "unicode/utf8"

// MatchDistcc reports whether input fully matches the regex `^distccd\[\d+\] (\([^\)]+\))? ?.*$`.
func MatchDistcc(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == 'd':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r == 'i':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r == 's':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == 't':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r == 'c':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r == 'c':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r == 'd':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r == '[':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '0' && r <= '9':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '0' && r <= '9':
				state = 9
			case r == ']':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r == ' ':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 12
			case r >= '\v' && r <= '\x1f':
				state = 12
			case r == ' ':
				state = 12
			case r >= '!' && r <= '\'':
				state = 12
			case r == '(':
				state = 13
			case r >= ')' && r <= '\U0010ffff':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 12
			case r >= '\v' && r <= '\U0010ffff':
				state = 12
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r == '\n':
				state = 15
			case r >= '\v' && r <= '(':
				state = 14
			case r == ')':
				state = 12
			case r >= '*' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 14
			case r == '\n':
				state = 15
			case r >= '\v' && r <= '(':
				state = 14
			case r == ')':
				state = 16
			case r >= '*' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '(':
				state = 15
			case r == ')':
				state = 16
			case r >= '*' && r <= '\U0010ffff':
				state = 15
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 12
			case r >= '\v' && r <= '\x1f':
				state = 12
			case r == ' ':
				state = 12
			case r >= '!' && r <= '\U0010ffff':
				state = 12
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 11, 12, 13, 14, 16:
		return true
	default:
		return false
	}
}
