// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[-\d]{10}\s[:\d]{8}\s(install|upgrade|remove|purge)\s\S+\s\S+\s\S+$`

package matchers

import "unicode/utf8"

// MatchDpkgAction reports whether input fully matches the regex `^[-\d]{10}\s[:\d]{8}\s(install|upgrade|remove|purge)\s\S+\s\S+\s\S+$`.
func MatchDpkgAction(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == '-':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r == '-':
				state = 2
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r == '-':
				state = 3
			case r >= '0' && r <= '9':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == '-':
				state = 4
			case r >= '0' && r <= '9':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r == '-':
				state = 5
			case r >= '0' && r <= '9':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r == '-':
				state = 6
			case r >= '0' && r <= '9':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r == '-':
				state = 7
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r == '-':
				state = 8
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r == '-':
				state = 9
			case r >= '0' && r <= '9':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r == '-':
				state = 10
			case r >= '0' && r <= '9':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\t' && r <= '\n':
				state = 11
			case r >= '\f' && r <= '\r':
				state = 11
			case r == ' ':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '0' && r <= ':':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= ':':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= ':':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= ':':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r >= '0' && r <= ':':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r >= '0' && r <= ':':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '0' && r <= ':':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r >= '0' && r <= ':':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\t' && r <= '\n':
				state = 20
			case r >= '\f' && r <= '\r':
				state = 20
			case r == ' ':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r == 'i':
				state = 21
			case r == 'p':
				state = 22
			case r == 'r':
				state = 23
			case r == 'u':
				state = 24
			default:
				return false
			}
		case 21:
			switch {
			case r == 'n':
				state = 25
			default:
				return false
			}
		case 22:
			switch {
			case r == 'u':
				state = 26
			default:
				return false
			}
		case 23:
			switch {
			case r == 'e':
				state = 27
			default:
				return false
			}
		case 24:
			switch {
			case r == 'p':
				state = 28
			default:
				return false
			}
		case 25:
			switch {
			case r == 's':
				state = 29
			default:
				return false
			}
		case 26:
			switch {
			case r == 'r':
				state = 30
			default:
				return false
			}
		case 27:
			switch {
			case r == 'm':
				state = 31
			default:
				return false
			}
		case 28:
			switch {
			case r == 'g':
				state = 32
			default:
				return false
			}
		case 29:
			switch {
			case r == 't':
				state = 33
			default:
				return false
			}
		case 30:
			switch {
			case r == 'g':
				state = 34
			default:
				return false
			}
		case 31:
			switch {
			case r == 'o':
				state = 35
			default:
				return false
			}
		case 32:
			switch {
			case r == 'r':
				state = 36
			default:
				return false
			}
		case 33:
			switch {
			case r == 'a':
				state = 37
			default:
				return false
			}
		case 34:
			switch {
			case r == 'e':
				state = 38
			default:
				return false
			}
		case 35:
			switch {
			case r == 'v':
				state = 39
			default:
				return false
			}
		case 36:
			switch {
			case r == 'a':
				state = 40
			default:
				return false
			}
		case 37:
			switch {
			case r == 'l':
				state = 41
			default:
				return false
			}
		case 38:
			switch {
			case r >= '\t' && r <= '\n':
				state = 42
			case r >= '\f' && r <= '\r':
				state = 42
			case r == ' ':
				state = 42
			default:
				return false
			}
		case 39:
			switch {
			case r == 'e':
				state = 38
			default:
				return false
			}
		case 40:
			switch {
			case r == 'd':
				state = 43
			default:
				return false
			}
		case 41:
			switch {
			case r == 'l':
				state = 38
			default:
				return false
			}
		case 42:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 44
			case r == '\v':
				state = 44
			case r >= '\x0e' && r <= '\x1f':
				state = 44
			case r >= '!' && r <= '\U0010ffff':
				state = 44
			default:
				return false
			}
		case 43:
			switch {
			case r == 'e':
				state = 38
			default:
				return false
			}
		case 44:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 44
			case r >= '\t' && r <= '\n':
				state = 45
			case r == '\v':
				state = 44
			case r >= '\f' && r <= '\r':
				state = 45
			case r >= '\x0e' && r <= '\x1f':
				state = 44
			case r == ' ':
				state = 45
			case r >= '!' && r <= '\U0010ffff':
				state = 44
			default:
				return false
			}
		case 45:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 46
			case r == '\v':
				state = 46
			case r >= '\x0e' && r <= '\x1f':
				state = 46
			case r >= '!' && r <= '\U0010ffff':
				state = 46
			default:
				return false
			}
		case 46:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 46
			case r >= '\t' && r <= '\n':
				state = 47
			case r == '\v':
				state = 46
			case r >= '\f' && r <= '\r':
				state = 47
			case r >= '\x0e' && r <= '\x1f':
				state = 46
			case r == ' ':
				state = 47
			case r >= '!' && r <= '\U0010ffff':
				state = 46
			default:
				return false
			}
		case 47:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 48
			case r == '\v':
				state = 48
			case r >= '\x0e' && r <= '\x1f':
				state = 48
			case r >= '!' && r <= '\U0010ffff':
				state = 48
			default:
				return false
			}
		case 48:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 48
			case r == '\v':
				state = 48
			case r >= '\x0e' && r <= '\x1f':
				state = 48
			case r >= '!' && r <= '\U0010ffff':
				state = 48
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 48
}
