// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\S{16}\s[<=\*][=>\*]\s\S+.*$`

package matchers

import "unicode/utf8"

// MatchEximAction reports whether input fully matches the regex `^\S{16}\s[<=\*][=>\*]\s\S+.*$`.
func MatchEximAction(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r == '\v':
				state = 1
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r >= '!' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 2
			case r == '\v':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 2
			case r >= '!' && r <= '\U0010ffff':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 3
			case r == '\v':
				state = 3
			case r >= '\x0e' && r <= '\x1f':
				state = 3
			case r >= '!' && r <= '\U0010ffff':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 4
			case r == '\v':
				state = 4
			case r >= '\x0e' && r <= '\x1f':
				state = 4
			case r >= '!' && r <= '\U0010ffff':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\v':
				state = 5
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r >= '!' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 6
			case r == '\v':
				state = 6
			case r >= '\x0e' && r <= '\x1f':
				state = 6
			case r >= '!' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 7
			case r == '\v':
				state = 7
			case r >= '\x0e' && r <= '\x1f':
				state = 7
			case r >= '!' && r <= '\U0010ffff':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 8
			case r == '\v':
				state = 8
			case r >= '\x0e' && r <= '\x1f':
				state = 8
			case r >= '!' && r <= '\U0010ffff':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 9
			case r == '\v':
				state = 9
			case r >= '\x0e' && r <= '\x1f':
				state = 9
			case r >= '!' && r <= '\U0010ffff':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 10
			case r == '\v':
				state = 10
			case r >= '\x0e' && r <= '\x1f':
				state = 10
			case r >= '!' && r <= '\U0010ffff':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 11
			case r == '\v':
				state = 11
			case r >= '\x0e' && r <= '\x1f':
				state = 11
			case r >= '!' && r <= '\U0010ffff':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 12
			case r == '\v':
				state = 12
			case r >= '\x0e' && r <= '\x1f':
				state = 12
			case r >= '!' && r <= '\U0010ffff':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 13
			case r == '\v':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 13
			case r >= '!' && r <= '\U0010ffff':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 14
			case r == '\v':
				state = 14
			case r >= '\x0e' && r <= '\x1f':
				state = 14
			case r >= '!' && r <= '\U0010ffff':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 15
			case r == '\v':
				state = 15
			case r >= '\x0e' && r <= '\x1f':
				state = 15
			case r >= '!' && r <= '\U0010ffff':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 16
			case r == '\v':
				state = 16
			case r >= '\x0e' && r <= '\x1f':
				state = 16
			case r >= '!' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\t' && r <= '\n':
				state = 17
			case r >= '\f' && r <= '\r':
				state = 17
			case r == ' ':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r == '*':
				state = 18
			case r >= '<' && r <= '=':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r == '*':
				state = 19
			case r >= '=' && r <= '>':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\t' && r <= '\n':
				state = 20
			case r >= '\f' && r <= '\r':
				state = 20
			case r == ' ':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 21
			case r == '\v':
				state = 21
			case r >= '\x0e' && r <= '\x1f':
				state = 21
			case r >= '!' && r <= '\U0010ffff':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 21
			case r == '\t':
				state = 22
			case r == '\v':
				state = 21
			case r >= '\f' && r <= '\r':
				state = 22
			case r >= '\x0e' && r <= '\x1f':
				state = 21
			case r == ' ':
				state = 22
			case r >= '!' && r <= '\U0010ffff':
				state = 21
			default:
				return false
			}
		case 22:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 22
			case r >= '\v' && r <= '\U0010ffff':
				state = 22
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 21, 22:
		return true
	default:
		return false
	}
}
