// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^.*reading message [^@]*@[^:]*:\d+ of \d+ .*$`

package matchers

import "unicode/utf8"

// MatchFetchmail reports whether input fully matches the regex `^.*reading message [^@]*@[^:]*:\d+ of \d+ .*$`.
func MatchFetchmail(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'd':
				state = 1
			case r == 'e':
				state = 3
			case r >= 'f' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '`':
				state = 1
			case r == 'a':
				state = 4
			case r >= 'b' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'c':
				state = 1
			case r == 'd':
				state = 5
			case r >= 'e' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'h':
				state = 1
			case r == 'i':
				state = 6
			case r >= 'j' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'm':
				state = 1
			case r == 'n':
				state = 7
			case r >= 'o' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'f':
				state = 1
			case r == 'g':
				state = 8
			case r >= 'h' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 9
			case r >= '!' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'l':
				state = 1
			case r == 'm':
				state = 10
			case r >= 'n' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'd':
				state = 1
			case r == 'e':
				state = 11
			case r >= 'f' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r == 's':
				state = 12
			case r >= 't' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 12:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r == 's':
				state = 13
			case r >= 't' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '`':
				state = 1
			case r == 'a':
				state = 14
			case r >= 'b' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'f':
				state = 1
			case r == 'g':
				state = 15
			case r >= 'h' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'd':
				state = 1
			case r == 'e':
				state = 16
			case r >= 'f' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 17
			case r >= '!' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\x00' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'd':
				state = 17
			case r == 'e':
				state = 24
			case r >= 'f' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\x00' && r <= '9':
				state = 21
			case r == ':':
				state = 25
			case r >= ';' && r <= '\U0010ffff':
				state = 21
			default:
				return false
			}
		case 22:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 26
			case r >= ':' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 23:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'd':
				state = 19
			case r == 'e':
				state = 27
			case r >= 'f' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= '`':
				state = 17
			case r == 'a':
				state = 28
			case r >= 'b' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 25:
			switch {
			case r >= '0' && r <= '9':
				state = 29
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 30
			case r >= '!' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 26
			case r >= ':' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 27:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= '`':
				state = 19
			case r == 'a':
				state = 31
			case r >= 'b' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'c':
				state = 17
			case r == 'd':
				state = 32
			case r >= 'e' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 29:
			switch {
			case r == ' ':
				state = 33
			case r >= '0' && r <= '9':
				state = 29
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'n':
				state = 1
			case r == 'o':
				state = 34
			case r >= 'p' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'c':
				state = 19
			case r == 'd':
				state = 35
			case r >= 'e' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'h':
				state = 17
			case r == 'i':
				state = 36
			case r >= 'j' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 33:
			switch {
			case r == 'o':
				state = 37
			default:
				return false
			}
		case 34:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'e':
				state = 1
			case r == 'f':
				state = 38
			case r >= 'g' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 35:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'h':
				state = 19
			case r == 'i':
				state = 39
			case r >= 'j' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 36:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'm':
				state = 17
			case r == 'n':
				state = 40
			case r >= 'o' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 37:
			switch {
			case r == 'f':
				state = 41
			default:
				return false
			}
		case 38:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 42
			case r >= '!' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 39:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'm':
				state = 19
			case r == 'n':
				state = 43
			case r >= 'o' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 40:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'f':
				state = 17
			case r == 'g':
				state = 44
			case r >= 'h' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 41:
			switch {
			case r == ' ':
				state = 45
			default:
				return false
			}
		case 42:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 46
			case r >= ':' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 43:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'f':
				state = 19
			case r == 'g':
				state = 47
			case r >= 'h' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 44:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 17
			case r == ' ':
				state = 48
			case r >= '!' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 45:
			switch {
			case r >= '0' && r <= '9':
				state = 49
			default:
				return false
			}
		case 46:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 50
			case r >= '!' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 46
			case r >= ':' && r <= 'q':
				state = 1
			case r == 'r':
				state = 2
			case r >= 's' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 47:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '\x1f':
				state = 19
			case r == ' ':
				state = 51
			case r >= '!' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 48:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'l':
				state = 17
			case r == 'm':
				state = 52
			case r >= 'n' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 49:
			switch {
			case r == ' ':
				state = 53
			case r >= '0' && r <= '9':
				state = 49
			default:
				return false
			}
		case 50:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 51:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'l':
				state = 19
			case r == 'm':
				state = 55
			case r >= 'n' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 52:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'd':
				state = 17
			case r == 'e':
				state = 56
			case r >= 'f' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 53:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 54:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'd':
				state = 50
			case r == 'e':
				state = 57
			case r >= 'f' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 55:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'd':
				state = 19
			case r == 'e':
				state = 58
			case r >= 'f' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 56:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r == 's':
				state = 59
			case r >= 't' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 57:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '`':
				state = 50
			case r == 'a':
				state = 60
			case r >= 'b' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 58:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r == 's':
				state = 61
			case r >= 't' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 59:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r == 's':
				state = 62
			case r >= 't' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 60:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'c':
				state = 50
			case r == 'd':
				state = 63
			case r >= 'e' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 61:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r == 's':
				state = 64
			case r >= 't' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 62:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= '`':
				state = 17
			case r == 'a':
				state = 65
			case r >= 'b' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 63:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'h':
				state = 50
			case r == 'i':
				state = 66
			case r >= 'j' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 64:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= '`':
				state = 19
			case r == 'a':
				state = 67
			case r >= 'b' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 65:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'f':
				state = 17
			case r == 'g':
				state = 68
			case r >= 'h' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 66:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'm':
				state = 50
			case r == 'n':
				state = 69
			case r >= 'o' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 67:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'f':
				state = 19
			case r == 'g':
				state = 70
			case r >= 'h' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 68:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'd':
				state = 17
			case r == 'e':
				state = 71
			case r >= 'f' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 69:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'f':
				state = 50
			case r == 'g':
				state = 72
			case r >= 'h' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 70:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'd':
				state = 19
			case r == 'e':
				state = 73
			case r >= 'f' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 71:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 17
			case r == ' ':
				state = 17
			case r >= '!' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 72:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '\x1f':
				state = 50
			case r == ' ':
				state = 74
			case r >= '!' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 73:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '\x1f':
				state = 19
			case r == ' ':
				state = 75
			case r >= '!' && r <= '9':
				state = 19
			case r == ':':
				state = 22
			case r >= ';' && r <= 'q':
				state = 19
			case r == 'r':
				state = 23
			case r >= 's' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 74:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'l':
				state = 50
			case r == 'm':
				state = 76
			case r >= 'n' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 75:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 76:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'd':
				state = 50
			case r == 'e':
				state = 80
			case r >= 'f' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 77:
			switch {
			case r >= '\x00' && r <= '9':
				state = 77
			case r == ':':
				state = 81
			case r >= ';' && r <= '?':
				state = 77
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 77
			default:
				return false
			}
		case 78:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '/':
				state = 17
			case r >= '0' && r <= '9':
				state = 82
			case r >= ':' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 79:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'd':
				state = 75
			case r == 'e':
				state = 83
			case r >= 'f' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 80:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r == 's':
				state = 84
			case r >= 't' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 81:
			switch {
			case r >= '\x00' && r <= '/':
				state = 18
			case r >= '0' && r <= '9':
				state = 85
			case r >= ':' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 82:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 17
			case r == ' ':
				state = 86
			case r >= '!' && r <= '/':
				state = 17
			case r >= '0' && r <= '9':
				state = 82
			case r >= ':' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 83:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= '`':
				state = 75
			case r == 'a':
				state = 87
			case r >= 'b' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 84:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r == 's':
				state = 88
			case r >= 't' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 85:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 18
			case r == ' ':
				state = 89
			case r >= '!' && r <= '/':
				state = 18
			case r >= '0' && r <= '9':
				state = 85
			case r >= ':' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 86:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'n':
				state = 17
			case r == 'o':
				state = 90
			case r >= 'p' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 87:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'c':
				state = 75
			case r == 'd':
				state = 91
			case r >= 'e' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 88:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '`':
				state = 50
			case r == 'a':
				state = 92
			case r >= 'b' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 89:
			switch {
			case r >= '\x00' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= 'n':
				state = 18
			case r == 'o':
				state = 93
			case r >= 'p' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 90:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'e':
				state = 17
			case r == 'f':
				state = 94
			case r >= 'g' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 91:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'h':
				state = 75
			case r == 'i':
				state = 95
			case r >= 'j' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 92:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'f':
				state = 50
			case r == 'g':
				state = 96
			case r >= 'h' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 93:
			switch {
			case r >= '\x00' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= 'e':
				state = 18
			case r == 'f':
				state = 97
			case r >= 'g' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 94:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 17
			case r == ' ':
				state = 98
			case r >= '!' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 95:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'm':
				state = 75
			case r == 'n':
				state = 99
			case r >= 'o' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 96:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'd':
				state = 50
			case r == 'e':
				state = 100
			case r >= 'f' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 97:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 18
			case r == ' ':
				state = 101
			case r >= '!' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 98:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '/':
				state = 17
			case r >= '0' && r <= '9':
				state = 102
			case r >= ':' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 99:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'f':
				state = 75
			case r == 'g':
				state = 103
			case r >= 'h' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 100:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '\x1f':
				state = 50
			case r == ' ':
				state = 104
			case r >= '!' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 101:
			switch {
			case r >= '\x00' && r <= '/':
				state = 18
			case r >= '0' && r <= '9':
				state = 105
			case r >= ':' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 102:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 17
			case r == ' ':
				state = 104
			case r >= '!' && r <= '/':
				state = 17
			case r >= '0' && r <= '9':
				state = 102
			case r >= ':' && r <= '?':
				state = 17
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 17
			case r == 'r':
				state = 20
			case r >= 's' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 103:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '\x1f':
				state = 75
			case r == ' ':
				state = 106
			case r >= '!' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 104:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 105:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 18
			case r == ' ':
				state = 109
			case r >= '!' && r <= '/':
				state = 18
			case r >= '0' && r <= '9':
				state = 105
			case r >= ':' && r <= '?':
				state = 18
			case r == '@':
				state = 21
			case r >= 'A' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 106:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'l':
				state = 75
			case r == 'm':
				state = 110
			case r >= 'n' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 107:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 108:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'd':
				state = 104
			case r == 'e':
				state = 113
			case r >= 'f' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 109:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 109
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 109
			case r == '@':
				state = 114
			case r >= 'A' && r <= '\U0010ffff':
				state = 109
			default:
				return false
			}
		case 110:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'd':
				state = 75
			case r == 'e':
				state = 115
			case r >= 'f' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 111:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '/':
				state = 50
			case r >= '0' && r <= '9':
				state = 116
			case r >= ':' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 112:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'd':
				state = 107
			case r == 'e':
				state = 117
			case r >= 'f' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 113:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= '`':
				state = 104
			case r == 'a':
				state = 118
			case r >= 'b' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 114:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 114
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 114
			case r == ':':
				state = 119
			case r >= ';' && r <= '\U0010ffff':
				state = 114
			default:
				return false
			}
		case 115:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r == 's':
				state = 120
			case r >= 't' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 116:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '\x1f':
				state = 50
			case r == ' ':
				state = 121
			case r >= '!' && r <= '/':
				state = 50
			case r >= '0' && r <= '9':
				state = 116
			case r >= ':' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 117:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= '`':
				state = 107
			case r == 'a':
				state = 122
			case r >= 'b' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 118:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'c':
				state = 104
			case r == 'd':
				state = 123
			case r >= 'e' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 119:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= '/':
				state = 53
			case r >= '0' && r <= '9':
				state = 124
			case r >= ':' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 120:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r == 's':
				state = 125
			case r >= 't' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 121:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'n':
				state = 50
			case r == 'o':
				state = 126
			case r >= 'p' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 122:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'c':
				state = 107
			case r == 'd':
				state = 127
			case r >= 'e' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 123:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'h':
				state = 104
			case r == 'i':
				state = 128
			case r >= 'j' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 124:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= '\x1f':
				state = 53
			case r == ' ':
				state = 129
			case r >= '!' && r <= '/':
				state = 53
			case r >= '0' && r <= '9':
				state = 124
			case r >= ':' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 125:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= '`':
				state = 75
			case r == 'a':
				state = 130
			case r >= 'b' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 126:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= 'e':
				state = 50
			case r == 'f':
				state = 131
			case r >= 'g' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 127:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'h':
				state = 107
			case r == 'i':
				state = 132
			case r >= 'j' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 128:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'm':
				state = 104
			case r == 'n':
				state = 133
			case r >= 'o' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 129:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= 'n':
				state = 53
			case r == 'o':
				state = 134
			case r >= 'p' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 130:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'f':
				state = 75
			case r == 'g':
				state = 135
			case r >= 'h' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 131:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '\x1f':
				state = 50
			case r == ' ':
				state = 136
			case r >= '!' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 132:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'm':
				state = 107
			case r == 'n':
				state = 137
			case r >= 'o' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 133:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'f':
				state = 104
			case r == 'g':
				state = 138
			case r >= 'h' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 134:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= 'e':
				state = 53
			case r == 'f':
				state = 139
			case r >= 'g' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 135:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'd':
				state = 75
			case r == 'e':
				state = 140
			case r >= 'f' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 136:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '/':
				state = 50
			case r >= '0' && r <= '9':
				state = 141
			case r >= ':' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 137:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'f':
				state = 107
			case r == 'g':
				state = 142
			case r >= 'h' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 138:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 104
			case r == ' ':
				state = 143
			case r >= '!' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 139:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= '\x1f':
				state = 53
			case r == ' ':
				state = 144
			case r >= '!' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 140:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 75
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '\x1f':
				state = 75
			case r == ' ':
				state = 75
			case r >= '!' && r <= '9':
				state = 75
			case r == ':':
				state = 78
			case r >= ';' && r <= '?':
				state = 75
			case r == '@':
				state = 19
			case r >= 'A' && r <= 'q':
				state = 75
			case r == 'r':
				state = 79
			case r >= 's' && r <= '\U0010ffff':
				state = 75
			default:
				return false
			}
		case 141:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 50
			case r >= '\v' && r <= '\x1f':
				state = 50
			case r == ' ':
				state = 50
			case r >= '!' && r <= '/':
				state = 50
			case r >= '0' && r <= '9':
				state = 141
			case r >= ':' && r <= 'q':
				state = 50
			case r == 'r':
				state = 54
			case r >= 's' && r <= '\U0010ffff':
				state = 50
			default:
				return false
			}
		case 142:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '\x1f':
				state = 107
			case r == ' ':
				state = 145
			case r >= '!' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 143:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'l':
				state = 104
			case r == 'm':
				state = 146
			case r >= 'n' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 144:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= '/':
				state = 53
			case r >= '0' && r <= '9':
				state = 147
			case r >= ':' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 145:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'l':
				state = 107
			case r == 'm':
				state = 148
			case r >= 'n' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 146:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'd':
				state = 104
			case r == 'e':
				state = 149
			case r >= 'f' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 147:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 53
			case r >= '\v' && r <= '\x1f':
				state = 53
			case r == ' ':
				state = 53
			case r >= '!' && r <= '/':
				state = 53
			case r >= '0' && r <= '9':
				state = 147
			case r >= ':' && r <= '\U0010ffff':
				state = 53
			default:
				return false
			}
		case 148:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'd':
				state = 107
			case r == 'e':
				state = 150
			case r >= 'f' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 149:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r == 's':
				state = 151
			case r >= 't' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 150:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r == 's':
				state = 152
			case r >= 't' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 151:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r == 's':
				state = 153
			case r >= 't' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 152:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r == 's':
				state = 154
			case r >= 't' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 153:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= '`':
				state = 104
			case r == 'a':
				state = 155
			case r >= 'b' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 154:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= '`':
				state = 107
			case r == 'a':
				state = 156
			case r >= 'b' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 155:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'f':
				state = 104
			case r == 'g':
				state = 157
			case r >= 'h' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 156:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'f':
				state = 107
			case r == 'g':
				state = 158
			case r >= 'h' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 157:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'd':
				state = 104
			case r == 'e':
				state = 159
			case r >= 'f' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 158:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'd':
				state = 107
			case r == 'e':
				state = 160
			case r >= 'f' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 159:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 104
			case r == ' ':
				state = 104
			case r >= '!' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 160:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 107
			case r == '\n':
				state = 21
			case r >= '\v' && r <= '\x1f':
				state = 107
			case r == ' ':
				state = 161
			case r >= '!' && r <= '9':
				state = 107
			case r == ':':
				state = 111
			case r >= ';' && r <= 'q':
				state = 107
			case r == 'r':
				state = 112
			case r >= 's' && r <= '\U0010ffff':
				state = 107
			default:
				return false
			}
		case 161:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 162:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '/':
				state = 104
			case r >= '0' && r <= '9':
				state = 164
			case r >= ':' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 163:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'd':
				state = 161
			case r == 'e':
				state = 165
			case r >= 'f' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 164:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 104
			case r == ' ':
				state = 166
			case r >= '!' && r <= '/':
				state = 104
			case r >= '0' && r <= '9':
				state = 164
			case r >= ':' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 165:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= '`':
				state = 161
			case r == 'a':
				state = 167
			case r >= 'b' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 166:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'n':
				state = 104
			case r == 'o':
				state = 168
			case r >= 'p' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 167:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'c':
				state = 161
			case r == 'd':
				state = 169
			case r >= 'e' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 168:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'e':
				state = 104
			case r == 'f':
				state = 170
			case r >= 'g' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 169:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'h':
				state = 161
			case r == 'i':
				state = 171
			case r >= 'j' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 170:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 104
			case r == ' ':
				state = 172
			case r >= '!' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 171:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'm':
				state = 161
			case r == 'n':
				state = 173
			case r >= 'o' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 172:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '/':
				state = 104
			case r >= '0' && r <= '9':
				state = 174
			case r >= ':' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 173:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'f':
				state = 161
			case r == 'g':
				state = 175
			case r >= 'h' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 174:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 104
			case r == '\n':
				state = 18
			case r >= '\v' && r <= '\x1f':
				state = 104
			case r == ' ':
				state = 104
			case r >= '!' && r <= '/':
				state = 104
			case r >= '0' && r <= '9':
				state = 174
			case r >= ':' && r <= '?':
				state = 104
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 104
			case r == 'r':
				state = 108
			case r >= 's' && r <= '\U0010ffff':
				state = 104
			default:
				return false
			}
		case 175:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '\x1f':
				state = 161
			case r == ' ':
				state = 176
			case r >= '!' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 176:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'l':
				state = 161
			case r == 'm':
				state = 177
			case r >= 'n' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 177:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'd':
				state = 161
			case r == 'e':
				state = 178
			case r >= 'f' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 178:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r == 's':
				state = 179
			case r >= 't' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 179:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r == 's':
				state = 180
			case r >= 't' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 180:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= '`':
				state = 161
			case r == 'a':
				state = 181
			case r >= 'b' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 181:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'f':
				state = 161
			case r == 'g':
				state = 182
			case r >= 'h' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 182:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'd':
				state = 161
			case r == 'e':
				state = 183
			case r >= 'f' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		case 183:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 161
			case r == '\n':
				state = 77
			case r >= '\v' && r <= '\x1f':
				state = 161
			case r == ' ':
				state = 161
			case r >= '!' && r <= '9':
				state = 161
			case r == ':':
				state = 162
			case r >= ';' && r <= '?':
				state = 161
			case r == '@':
				state = 107
			case r >= 'A' && r <= 'q':
				state = 161
			case r == 'r':
				state = 163
			case r >= 's' && r <= '\U0010ffff':
				state = 161
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 50, 53, 54, 57, 60, 63, 66, 69, 72, 74, 76, 80, 84, 88, 92, 96, 100, 104, 107, 108, 109, 111, 112, 113, 114, 116, 117, 118, 119, 121, 122, 123, 124, 126, 127, 128, 129, 131, 132, 133, 134, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183:
		return true
	default:
		return false
	}
}
