// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\[\w{3}\s\w{3}\s{1,2}\d{1,2}\s\d{2}:\d{2}:\d{2}\s\d{4}\]\s\[\w*\]\s.*$`

package matchers

import "unicode/utf8"

// MatchHttpdError reports whether input fully matches the regex `^\[\w{3}\s\w{3}\s{1,2}\d{1,2}\s\d{2}:\d{2}:\d{2}\s\d{4}\]\s\[\w*\]\s.*$`.
func MatchHttpdError(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == '[':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			case r >= 'A' && r <= 'Z':
				state = 2
			case r == '_':
				state = 2
			case r >= 'a' && r <= 'z':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 3
			case r == '_':
				state = 3
			case r >= 'a' && r <= 'z':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '_':
				state = 4
			case r >= 'a' && r <= 'z':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\t' && r <= '\n':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 5
			case r == ' ':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '0' && r <= '9':
				state = 6
			case r >= 'A' && r <= 'Z':
				state = 6
			case r == '_':
				state = 6
			case r >= 'a' && r <= 'z':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '0' && r <= '9':
				state = 7
			case r >= 'A' && r <= 'Z':
				state = 7
			case r == '_':
				state = 7
			case r >= 'a' && r <= 'z':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r >= '0' && r <= '9':
				state = 8
			case r >= 'A' && r <= 'Z':
				state = 8
			case r == '_':
				state = 8
			case r >= 'a' && r <= 'z':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\t' && r <= '\n':
				state = 9
			case r >= '\f' && r <= '\r':
				state = 9
			case r == ' ':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\t' && r <= '\n':
				state = 10
			case r >= '\f' && r <= '\r':
				state = 10
			case r == ' ':
				state = 10
			case r >= '0' && r <= '9':
				state = 11
			default:
				return false
			}
		case 10:
			switch {
			case r >= '0' && r <= '9':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\t' && r <= '\n':
				state = 12
			case r >= '\f' && r <= '\r':
				state = 12
			case r == ' ':
				state = 12
			case r >= '0' && r <= '9':
				state = 13
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\t' && r <= '\n':
				state = 12
			case r >= '\f' && r <= '\r':
				state = 12
			case r == ' ':
				state = 12
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r == ':':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r >= '0' && r <= '9':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '0' && r <= '9':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r == ':':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r >= '0' && r <= '9':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r >= '0' && r <= '9':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\t' && r <= '\n':
				state = 22
			case r >= '\f' && r <= '\r':
				state = 22
			case r == ' ':
				state = 22
			default:
				return false
			}
		case 22:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r >= '0' && r <= '9':
				state = 24
			default:
				return false
			}
		case 24:
			switch {
			case r >= '0' && r <= '9':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '0' && r <= '9':
				state = 26
			default:
				return false
			}
		case 26:
			switch {
			case r == ']':
				state = 27
			default:
				return false
			}
		case 27:
			switch {
			case r >= '\t' && r <= '\n':
				state = 28
			case r >= '\f' && r <= '\r':
				state = 28
			case r == ' ':
				state = 28
			default:
				return false
			}
		case 28:
			switch {
			case r == '[':
				state = 29
			default:
				return false
			}
		case 29:
			switch {
			case r >= '0' && r <= '9':
				state = 29
			case r >= 'A' && r <= 'Z':
				state = 29
			case r == ']':
				state = 30
			case r == '_':
				state = 29
			case r >= 'a' && r <= 'z':
				state = 29
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\t' && r <= '\n':
				state = 31
			case r >= '\f' && r <= '\r':
				state = 31
			case r == ' ':
				state = 31
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 31
			case r >= '\v' && r <= '\U0010ffff':
				state = 31
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 31
}
