// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\[\d+/.../\d+:\d+:\d+:\d+\] \[\d+:[^\]]*\] \[\d+/.../\d+:\d+:\d+:\d+\] Bandwidth:[\d\.]+[^ ]* Sources:\d+ Clients:\d+ Admins:\d+.*$`

package matchers

import "unicode/utf8"

// MatchIcecastUsage reports whether input fully matches the regex `^\[\d+/.../\d+:\d+:\d+:\d+\] \[\d+:[^\]]*\] \[\d+/.../\d+:\d+:\d+:\d+\] Bandwidth:[\d\.]+[^ ]* Sources:\d+ Clients:\d+ Admins:\d+.*$`.
func MatchIcecastUsage(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == '[':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r == '/':
				state = 3
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 4
			case r >= '\v' && r <= '\U0010ffff':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r == '/':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '0' && r <= '9':
				state = 8
			case r == ':':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			case r == ':':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			case r == ':':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			case r == ']':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r == ' ':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r == '[':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '0' && r <= '9':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r >= '0' && r <= '9':
				state = 18
			case r == ':':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\x00' && r <= '\\':
				state = 19
			case r == ']':
				state = 20
			case r >= '^' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 20:
			switch {
			case r == ' ':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case r == '[':
				state = 22
			default:
				return false
			}
		case 22:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r == '/':
				state = 24
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 25
			case r >= '\v' && r <= '\U0010ffff':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 26
			case r >= '\v' && r <= '\U0010ffff':
				state = 26
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 27
			case r >= '\v' && r <= '\U0010ffff':
				state = 27
			default:
				return false
			}
		case 27:
			switch {
			case r == '/':
				state = 28
			default:
				return false
			}
		case 28:
			switch {
			case r >= '0' && r <= '9':
				state = 29
			default:
				return false
			}
		case 29:
			switch {
			case r >= '0' && r <= '9':
				state = 29
			case r == ':':
				state = 30
			default:
				return false
			}
		case 30:
			switch {
			case r >= '0' && r <= '9':
				state = 31
			default:
				return false
			}
		case 31:
			switch {
			case r >= '0' && r <= '9':
				state = 31
			case r == ':':
				state = 32
			default:
				return false
			}
		case 32:
			switch {
			case r >= '0' && r <= '9':
				state = 33
			default:
				return false
			}
		case 33:
			switch {
			case r >= '0' && r <= '9':
				state = 33
			case r == ':':
				state = 34
			default:
				return false
			}
		case 34:
			switch {
			case r >= '0' && r <= '9':
				state = 35
			default:
				return false
			}
		case 35:
			switch {
			case r >= '0' && r <= '9':
				state = 35
			case r == ']':
				state = 36
			default:
				return false
			}
		case 36:
			switch {
			case r == ' ':
				state = 37
			default:
				return false
			}
		case 37:
			switch {
			case r == 'B':
				state = 38
			default:
				return false
			}
		case 38:
			switch {
			case r == 'a':
				state = 39
			default:
				return false
			}
		case 39:
			switch {
			case r == 'n':
				state = 40
			default:
				return false
			}
		case 40:
			switch {
			case r == 'd':
				state = 41
			default:
				return false
			}
		case 41:
			switch {
			case r == 'w':
				state = 42
			default:
				return false
			}
		case 42:
			switch {
			case r == 'i':
				state = 43
			default:
				return false
			}
		case 43:
			switch {
			case r == 'd':
				state = 44
			default:
				return false
			}
		case 44:
			switch {
			case r == 't':
				state = 45
			default:
				return false
			}
		case 45:
			switch {
			case r == 'h':
				state = 46
			default:
				return false
			}
		case 46:
			switch {
			case r == ':':
				state = 47
			default:
				return false
			}
		case 47:
			switch {
			case r == '.':
				state = 48
			case r >= '0' && r <= '9':
				state = 48
			default:
				return false
			}
		case 48:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 49
			case r == ' ':
				state = 50
			case r >= '!' && r <= '-':
				state = 49
			case r == '.':
				state = 48
			case r == '/':
				state = 49
			case r >= '0' && r <= '9':
				state = 48
			case r >= ':' && r <= '\U0010ffff':
				state = 49
			default:
				return false
			}
		case 49:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 49
			case r == ' ':
				state = 50
			case r >= '!' && r <= '\U0010ffff':
				state = 49
			default:
				return false
			}
		case 50:
			switch {
			case r == 'S':
				state = 51
			default:
				return false
			}
		case 51:
			switch {
			case r == 'o':
				state = 52
			default:
				return false
			}
		case 52:
			switch {
			case r == 'u':
				state = 53
			default:
				return false
			}
		case 53:
			switch {
			case r == 'r':
				state = 54
			default:
				return false
			}
		case 54:
			switch {
			case r == 'c':
				state = 55
			default:
				return false
			}
		case 55:
			switch {
			case r == 'e':
				state = 56
			default:
				return false
			}
		case 56:
			switch {
			case r == 's':
				state = 57
			default:
				return false
			}
		case 57:
			switch {
			case r == ':':
				state = 58
			default:
				return false
			}
		case 58:
			switch {
			case r >= '0' && r <= '9':
				state = 59
			default:
				return false
			}
		case 59:
			switch {
			case r == ' ':
				state = 60
			case r >= '0' && r <= '9':
				state = 59
			default:
				return false
			}
		case 60:
			switch {
			case r == 'C':
				state = 61
			default:
				return false
			}
		case 61:
			switch {
			case r == 'l':
				state = 62
			default:
				return false
			}
		case 62:
			switch {
			case r == 'i':
				state = 63
			default:
				return false
			}
		case 63:
			switch {
			case r == 'e':
				state = 64
			default:
				return false
			}
		case 64:
			switch {
			case r == 'n':
				state = 65
			default:
				return false
			}
		case 65:
			switch {
			case r == 't':
				state = 66
			default:
				return false
			}
		case 66:
			switch {
			case r == 's':
				state = 67
			default:
				return false
			}
		case 67:
			switch {
			case r == ':':
				state = 68
			default:
				return false
			}
		case 68:
			switch {
			case r >= '0' && r <= '9':
				state = 69
			default:
				return false
			}
		case 69:
			switch {
			case r == ' ':
				state = 70
			case r >= '0' && r <= '9':
				state = 69
			default:
				return false
			}
		case 70:
			switch {
			case r == 'A':
				state = 71
			default:
				return false
			}
		case 71:
			switch {
			case r == 'd':
				state = 72
			default:
				return false
			}
		case 72:
			switch {
			case r == 'm':
				state = 73
			default:
				return false
			}
		case 73:
			switch {
			case r == 'i':
				state = 74
			default:
				return false
			}
		case 74:
			switch {
			case r == 'n':
				state = 75
			default:
				return false
			}
		case 75:
			switch {
			case r == 's':
				state = 76
			default:
				return false
			}
		case 76:
			switch {
			case r == ':':
				state = 77
			default:
				return false
			}
		case 77:
			switch {
			case r >= '0' && r <= '9':
				state = 78
			default:
				return false
			}
		case 78:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 79
			case r >= '\v' && r <= '/':
				state = 79
			case r >= '0' && r <= '9':
				state = 78
			case r >= ':' && r <= '\U0010ffff':
				state = 79
			default:
				return false
			}
		case 79:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 79
			case r >= '\v' && r <= '\U0010ffff':
				state = 79
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 78, 79:
		return true
	default:
		return false
	}
}
