// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d+ \d+:\d+:\d+ \d+\s+\[[\dxa-fA-F]+\]statistics\(\): \S+\s*: \d+.*$`

package matchers

import "unicode/utf8"

// MatchOops reports whether input fully matches the regex `^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d+ \d+:\d+:\d+ \d+\s+\[[\dxa-fA-F]+\]statistics\(\): \S+\s*: \d+.*$`.
func MatchOops(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == 'F':
				state = 1
			case r == 'M':
				state = 2
			case r == 'S':
				state = 3
			case r == 'T':
				state = 4
			case r == 'W':
				state = 5
			default:
				return false
			}
		case 1:
			switch {
			case r == 'r':
				state = 6
			default:
				return false
			}
		case 2:
			switch {
			case r == 'o':
				state = 7
			default:
				return false
			}
		case 3:
			switch {
			case r == 'a':
				state = 8
			case r == 'u':
				state = 9
			default:
				return false
			}
		case 4:
			switch {
			case r == 'h':
				state = 10
			case r == 'u':
				state = 11
			default:
				return false
			}
		case 5:
			switch {
			case r == 'e':
				state = 12
			default:
				return false
			}
		case 6:
			switch {
			case r == 'i':
				state = 13
			default:
				return false
			}
		case 7:
			switch {
			case r == 'n':
				state = 13
			default:
				return false
			}
		case 8:
			switch {
			case r == 't':
				state = 13
			default:
				return false
			}
		case 9:
			switch {
			case r == 'n':
				state = 13
			default:
				return false
			}
		case 10:
			switch {
			case r == 'u':
				state = 13
			default:
				return false
			}
		case 11:
			switch {
			case r == 'e':
				state = 13
			default:
				return false
			}
		case 12:
			switch {
			case r == 'd':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r == ' ':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r == 'A':
				state = 15
			case r == 'D':
				state = 16
			case r == 'F':
				state = 17
			case r == 'J':
				state = 18
			case r == 'M':
				state = 19
			case r == 'N':
				state = 20
			case r == 'O':
				state = 21
			case r == 'S':
				state = 22
			default:
				return false
			}
		case 15:
			switch {
			case r == 'p':
				state = 23
			case r == 'u':
				state = 24
			default:
				return false
			}
		case 16:
			switch {
			case r == 'e':
				state = 25
			default:
				return false
			}
		case 17:
			switch {
			case r == 'e':
				state = 26
			default:
				return false
			}
		case 18:
			switch {
			case r == 'a':
				state = 27
			case r == 'u':
				state = 28
			default:
				return false
			}
		case 19:
			switch {
			case r == 'a':
				state = 29
			default:
				return false
			}
		case 20:
			switch {
			case r == 'o':
				state = 30
			default:
				return false
			}
		case 21:
			switch {
			case r == 'c':
				state = 31
			default:
				return false
			}
		case 22:
			switch {
			case r == 'e':
				state = 32
			default:
				return false
			}
		case 23:
			switch {
			case r == 'r':
				state = 33
			default:
				return false
			}
		case 24:
			switch {
			case r == 'g':
				state = 33
			default:
				return false
			}
		case 25:
			switch {
			case r == 'c':
				state = 33
			default:
				return false
			}
		case 26:
			switch {
			case r == 'b':
				state = 33
			default:
				return false
			}
		case 27:
			switch {
			case r == 'n':
				state = 33
			default:
				return false
			}
		case 28:
			switch {
			case r == 'l':
				state = 33
			case r == 'n':
				state = 33
			default:
				return false
			}
		case 29:
			switch {
			case r == 'r':
				state = 33
			case r == 'y':
				state = 33
			default:
				return false
			}
		case 30:
			switch {
			case r == 'v':
				state = 33
			default:
				return false
			}
		case 31:
			switch {
			case r == 't':
				state = 33
			default:
				return false
			}
		case 32:
			switch {
			case r == 'p':
				state = 33
			default:
				return false
			}
		case 33:
			switch {
			case r == ' ':
				state = 34
			default:
				return false
			}
		case 34:
			switch {
			case r >= '0' && r <= '9':
				state = 35
			default:
				return false
			}
		case 35:
			switch {
			case r == ' ':
				state = 36
			case r >= '0' && r <= '9':
				state = 35
			default:
				return false
			}
		case 36:
			switch {
			case r >= '0' && r <= '9':
				state = 37
			default:
				return false
			}
		case 37:
			switch {
			case r >= '0' && r <= '9':
				state = 37
			case r == ':':
				state = 38
			default:
				return false
			}
		case 38:
			switch {
			case r >= '0' && r <= '9':
				state = 39
			default:
				return false
			}
		case 39:
			switch {
			case r >= '0' && r <= '9':
				state = 39
			case r == ':':
				state = 40
			default:
				return false
			}
		case 40:
			switch {
			case r >= '0' && r <= '9':
				state = 41
			default:
				return false
			}
		case 41:
			switch {
			case r == ' ':
				state = 42
			case r >= '0' && r <= '9':
				state = 41
			default:
				return false
			}
		case 42:
			switch {
			case r >= '0' && r <= '9':
				state = 43
			default:
				return false
			}
		case 43:
			switch {
			case r >= '\t' && r <= '\n':
				state = 44
			case r >= '\f' && r <= '\r':
				state = 44
			case r == ' ':
				state = 44
			case r >= '0' && r <= '9':
				state = 43
			default:
				return false
			}
		case 44:
			switch {
			case r >= '\t' && r <= '\n':
				state = 44
			case r >= '\f' && r <= '\r':
				state = 44
			case r == ' ':
				state = 44
			case r == '[':
				state = 45
			default:
				return false
			}
		case 45:
			switch {
			case r >= '0' && r <= '9':
				state = 46
			case r >= 'A' && r <= 'F':
				state = 46
			case r >= 'a' && r <= 'f':
				state = 46
			case r == 'x':
				state = 46
			default:
				return false
			}
		case 46:
			switch {
			case r >= '0' && r <= '9':
				state = 46
			case r >= 'A' && r <= 'F':
				state = 46
			case r == ']':
				state = 47
			case r >= 'a' && r <= 'f':
				state = 46
			case r == 'x':
				state = 46
			default:
				return false
			}
		case 47:
			switch {
			case r == 's':
				state = 48
			default:
				return false
			}
		case 48:
			switch {
			case r == 't':
				state = 49
			default:
				return false
			}
		case 49:
			switch {
			case r == 'a':
				state = 50
			default:
				return false
			}
		case 50:
			switch {
			case r == 't':
				state = 51
			default:
				return false
			}
		case 51:
			switch {
			case r == 'i':
				state = 52
			default:
				return false
			}
		case 52:
			switch {
			case r == 's':
				state = 53
			default:
				return false
			}
		case 53:
			switch {
			case r == 't':
				state = 54
			default:
				return false
			}
		case 54:
			switch {
			case r == 'i':
				state = 55
			default:
				return false
			}
		case 55:
			switch {
			case r == 'c':
				state = 56
			default:
				return false
			}
		case 56:
			switch {
			case r == 's':
				state = 57
			default:
				return false
			}
		case 57:
			switch {
			case r == '(':
				state = 58
			default:
				return false
			}
		case 58:
			switch {
			case r == ')':
				state = 59
			default:
				return false
			}
		case 59:
			switch {
			case r == ':':
				state = 60
			default:
				return false
			}
		case 60:
			switch {
			case r == ' ':
				state = 61
			default:
				return false
			}
		case 61:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 62
			case r == '\v':
				state = 62
			case r >= '\x0e' && r <= '\x1f':
				state = 62
			case r >= '!' && r <= '\U0010ffff':
				state = 62
			default:
				return false
			}
		case 62:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 62
			case r >= '\t' && r <= '\n':
				state = 63
			case r == '\v':
				state = 62
			case r >= '\f' && r <= '\r':
				state = 63
			case r >= '\x0e' && r <= '\x1f':
				state = 62
			case r == ' ':
				state = 63
			case r >= '!' && r <= '9':
				state = 62
			case r == ':':
				state = 64
			case r >= ';' && r <= '\U0010ffff':
				state = 62
			default:
				return false
			}
		case 63:
			switch {
			case r >= '\t' && r <= '\n':
				state = 63
			case r >= '\f' && r <= '\r':
				state = 63
			case r == ' ':
				state = 63
			case r == ':':
				state = 65
			default:
				return false
			}
		case 64:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 62
			case r >= '\t' && r <= '\n':
				state = 63
			case r == '\v':
				state = 62
			case r >= '\f' && r <= '\r':
				state = 63
			case r >= '\x0e' && r <= '\x1f':
				state = 62
			case r == ' ':
				state = 66
			case r >= '!' && r <= '9':
				state = 62
			case r == ':':
				state = 64
			case r >= ';' && r <= '\U0010ffff':
				state = 62
			default:
				return false
			}
		case 65:
			switch {
			case r == ' ':
				state = 67
			default:
				return false
			}
		case 66:
			switch {
			case r >= '\t' && r <= '\n':
				state = 63
			case r >= '\f' && r <= '\r':
				state = 63
			case r == ' ':
				state = 63
			case r >= '0' && r <= '9':
				state = 68
			case r == ':':
				state = 65
			default:
				return false
			}
		case 67:
			switch {
			case r >= '0' && r <= '9':
				state = 68
			default:
				return false
			}
		case 68:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 69
			case r >= '\v' && r <= '/':
				state = 69
			case r >= '0' && r <= '9':
				state = 68
			case r >= ':' && r <= '\U0010ffff':
				state = 69
			default:
				return false
			}
		case 69:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 69
			case r >= '\v' && r <= '\U0010ffff':
				state = 69
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 68, 69:
		return true
	default:
		return false
	}
}
