// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\[\d+-...-\d+ \d+:\d+:\d+\] PHP .*$`

package matchers

import "unicode/utf8"

// MatchPhp reports whether input fully matches the regex `^\[\d+-...-\d+ \d+:\d+:\d+\] PHP .*$`.
func MatchPhp(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == '[':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r == '-':
				state = 3
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 4
			case r >= '\v' && r <= '\U0010ffff':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r == '-':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r == ' ':
				state = 9
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 9:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			case r == ':':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			case r == ':':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			case r == ']':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r == ' ':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r == 'P':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r == 'H':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r == 'P':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r == ' ':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 20
			case r >= '\v' && r <= '\U0010ffff':
				state = 20
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 20
}
