// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[\dA-F]+: (client|to|message-id|uid|resent-message-id|from)=.*$`

package matchers

import "unicode/utf8"

// MatchPostfix reports whether input fully matches the regex `^[\dA-F]+: (client|to|message-id|uid|resent-message-id|from)=.*$`.
func MatchPostfix(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			case r >= 'A' && r <= 'F':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			case r == ':':
				state = 2
			case r >= 'A' && r <= 'F':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r == ' ':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == 'c':
				state = 4
			case r == 'f':
				state = 5
			case r == 'm':
				state = 6
			case r == 'r':
				state = 7
			case r == 't':
				state = 8
			case r == 'u':
				state = 9
			default:
				return false
			}
		case 4:
			switch {
			case r == 'l':
				state = 10
			default:
				return false
			}
		case 5:
			switch {
			case r == 'r':
				state = 11
			default:
				return false
			}
		case 6:
			switch {
			case r == 'e':
				state = 12
			default:
				return false
			}
		case 7:
			switch {
			case r == 'e':
				state = 13
			default:
				return false
			}
		case 8:
			switch {
			case r == 'o':
				state = 14
			default:
				return false
			}
		case 9:
			switch {
			case r == 'i':
				state = 15
			default:
				return false
			}
		case 10:
			switch {
			case r == 'i':
				state = 16
			default:
				return false
			}
		case 11:
			switch {
			case r == 'o':
				state = 17
			default:
				return false
			}
		case 12:
			switch {
			case r == 's':
				state = 18
			default:
				return false
			}
		case 13:
			switch {
			case r == 's':
				state = 19
			default:
				return false
			}
		case 14:
			switch {
			case r == '=':
				state = 20
			default:
				return false
			}
		case 15:
			switch {
			case r == 'd':
				state = 14
			default:
				return false
			}
		case 16:
			switch {
			case r == 'e':
				state = 21
			default:
				return false
			}
		case 17:
			switch {
			case r == 'm':
				state = 14
			default:
				return false
			}
		case 18:
			switch {
			case r == 's':
				state = 22
			default:
				return false
			}
		case 19:
			switch {
			case r == 'e':
				state = 23
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 20
			case r >= '\v' && r <= '\U0010ffff':
				state = 20
			default:
				return false
			}
		case 21:
			switch {
			case r == 'n':
				state = 24
			default:
				return false
			}
		case 22:
			switch {
			case r == 'a':
				state = 25
			default:
				return false
			}
		case 23:
			switch {
			case r == 'n':
				state = 26
			default:
				return false
			}
		case 24:
			switch {
			case r == 't':
				state = 14
			default:
				return false
			}
		case 25:
			switch {
			case r == 'g':
				state = 27
			default:
				return false
			}
		case 26:
			switch {
			case r == 't':
				state = 28
			default:
				return false
			}
		case 27:
			switch {
			case r == 'e':
				state = 29
			default:
				return false
			}
		case 28:
			switch {
			case r == '-':
				state = 30
			default:
				return false
			}
		case 29:
			switch {
			case r == '-':
				state = 31
			default:
				return false
			}
		case 30:
			switch {
			case r == 'm':
				state = 32
			default:
				return false
			}
		case 31:
			switch {
			case r == 'i':
				state = 33
			default:
				return false
			}
		case 32:
			switch {
			case r == 'e':
				state = 34
			default:
				return false
			}
		case 33:
			switch {
			case r == 'd':
				state = 14
			default:
				return false
			}
		case 34:
			switch {
			case r == 's':
				state = 35
			default:
				return false
			}
		case 35:
			switch {
			case r == 's':
				state = 36
			default:
				return false
			}
		case 36:
			switch {
			case r == 'a':
				state = 37
			default:
				return false
			}
		case 37:
			switch {
			case r == 'g':
				state = 38
			default:
				return false
			}
		case 38:
			switch {
			case r == 'e':
				state = 39
			default:
				return false
			}
		case 39:
			switch {
			case r == '-':
				state = 40
			default:
				return false
			}
		case 40:
			switch {
			case r == 'i':
				state = 41
			default:
				return false
			}
		case 41:
			switch {
			case r == 'd':
				state = 14
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 20
}
