// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\s*(>?From|Subject:|Folder:)?\s\S+(\s+)?.*$`

package matchers

import "unicode/utf8"

// MatchProcmail reports whether input fully matches the regex `^\s*(>?From|Subject:|Folder:)?\s\S+(\s+)?.*$`.
func MatchProcmail(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\t' && r <= '\n':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 1
			case r == ' ':
				state = 1
			case r == '>':
				state = 2
			case r == 'F':
				state = 3
			case r == 'S':
				state = 4
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r >= '\t' && r <= '\n':
				state = 1
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 1
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 1
			case r >= '!' && r <= '=':
				state = 5
			case r == '>':
				state = 6
			case r >= '?' && r <= 'E':
				state = 5
			case r == 'F':
				state = 7
			case r >= 'G' && r <= 'R':
				state = 5
			case r == 'S':
				state = 8
			case r >= 'T' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 2:
			switch {
			case r == 'F':
				state = 9
			default:
				return false
			}
		case 3:
			switch {
			case r == 'o':
				state = 10
			case r == 'r':
				state = 11
			default:
				return false
			}
		case 4:
			switch {
			case r == 'u':
				state = 12
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'E':
				state = 5
			case r == 'F':
				state = 14
			case r >= 'G' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'n':
				state = 5
			case r == 'o':
				state = 15
			case r >= 'p' && r <= 'q':
				state = 5
			case r == 'r':
				state = 16
			case r >= 's' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 't':
				state = 5
			case r == 'u':
				state = 17
			case r >= 'v' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 9:
			switch {
			case r == 'r':
				state = 11
			default:
				return false
			}
		case 10:
			switch {
			case r == 'l':
				state = 18
			default:
				return false
			}
		case 11:
			switch {
			case r == 'o':
				state = 19
			default:
				return false
			}
		case 12:
			switch {
			case r == 'b':
				state = 20
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 21
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 21
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 21
			case r == ' ':
				state = 13
			case r >= '!' && r <= '\U0010ffff':
				state = 21
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'q':
				state = 5
			case r == 'r':
				state = 16
			case r >= 's' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'k':
				state = 5
			case r == 'l':
				state = 22
			case r >= 'm' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'n':
				state = 5
			case r == 'o':
				state = 23
			case r >= 'p' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'a':
				state = 5
			case r == 'b':
				state = 24
			case r >= 'c' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 18:
			switch {
			case r == 'd':
				state = 25
			default:
				return false
			}
		case 19:
			switch {
			case r == 'm':
				state = 26
			default:
				return false
			}
		case 20:
			switch {
			case r == 'j':
				state = 27
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 21
			case r >= '\v' && r <= '\U0010ffff':
				state = 21
			default:
				return false
			}
		case 22:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'c':
				state = 5
			case r == 'd':
				state = 28
			case r >= 'e' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 23:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'l':
				state = 5
			case r == 'm':
				state = 29
			case r >= 'n' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'i':
				state = 5
			case r == 'j':
				state = 30
			case r >= 'k' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 25:
			switch {
			case r == 'e':
				state = 31
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\t' && r <= '\n':
				state = 32
			case r >= '\f' && r <= '\r':
				state = 32
			case r == ' ':
				state = 32
			default:
				return false
			}
		case 27:
			switch {
			case r == 'e':
				state = 33
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'd':
				state = 5
			case r == 'e':
				state = 34
			case r >= 'f' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 29:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 35
			case r == '\n':
				state = 35
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 35
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 35
			case r >= '!' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'd':
				state = 5
			case r == 'e':
				state = 36
			case r >= 'f' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 31:
			switch {
			case r == 'r':
				state = 37
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\v':
				state = 5
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r >= '!' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 33:
			switch {
			case r == 'c':
				state = 38
			default:
				return false
			}
		case 34:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'q':
				state = 5
			case r == 'r':
				state = 39
			case r >= 's' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 35:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 36:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 'b':
				state = 5
			case r == 'c':
				state = 40
			case r >= 'd' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 37:
			switch {
			case r == ':':
				state = 26
			default:
				return false
			}
		case 38:
			switch {
			case r == 't':
				state = 41
			default:
				return false
			}
		case 39:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= '9':
				state = 5
			case r == ':':
				state = 29
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 40:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= 's':
				state = 5
			case r == 't':
				state = 42
			case r >= 'u' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 41:
			switch {
			case r == ':':
				state = 26
			default:
				return false
			}
		case 42:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 5
			case r == '\t':
				state = 13
			case r == '\n':
				state = 13
			case r == '\v':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 13
			case r >= '\x0e' && r <= '\x1f':
				state = 5
			case r == ' ':
				state = 13
			case r >= '!' && r <= '9':
				state = 5
			case r == ':':
				state = 29
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 5, 6, 7, 8, 13, 14, 15, 16, 17, 21, 22, 23, 24, 28, 29, 30, 34, 35, 36, 39, 40, 42:
		return true
	default:
		return false
	}
}
