// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\d+\.\d+\.\d+\.\d+ \S+ \S+ \[\d{2}/.{3}/\d{4}:\d{2}:\d{2}:\d{2} [-+]\d{4}\] "[A-Z]+ [^"]+" \d{3} (-|\d+)$`

package matchers

import "unicode/utf8"

// MatchProftpdAccess reports whether input fully matches the regex `^\d+\.\d+\.\d+\.\d+ \S+ \S+ \[\d{2}/.{3}/\d{4}:\d{2}:\d{2}:\d{2} [-+]\d{4}\] "[A-Z]+ [^"]+" \d{3} (-|\d+)$`.
func MatchProftpdAccess(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r == '.':
				state = 2
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == '.':
				state = 4
			case r >= '0' && r <= '9':
				state = 3
			default:
				return false
			}
		case 4:
			switch {
			case r >= '0' && r <= '9':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r == '.':
				state = 6
			case r >= '0' && r <= '9':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r == ' ':
				state = 8
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 9
			case r == '\v':
				state = 9
			case r >= '\x0e' && r <= '\x1f':
				state = 9
			case r >= '!' && r <= '\U0010ffff':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 9
			case r == '\v':
				state = 9
			case r >= '\x0e' && r <= '\x1f':
				state = 9
			case r == ' ':
				state = 10
			case r >= '!' && r <= '\U0010ffff':
				state = 9
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 11
			case r == '\v':
				state = 11
			case r >= '\x0e' && r <= '\x1f':
				state = 11
			case r >= '!' && r <= '\U0010ffff':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 11
			case r == '\v':
				state = 11
			case r >= '\x0e' && r <= '\x1f':
				state = 11
			case r == ' ':
				state = 12
			case r >= '!' && r <= '\U0010ffff':
				state = 11
			default:
				return false
			}
		case 12:
			switch {
			case r == '[':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r == '/':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 17
			case r >= '\v' && r <= '\U0010ffff':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 18
			case r >= '\v' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r >= '\v' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r == '/':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r >= '0' && r <= '9':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case r >= '0' && r <= '9':
				state = 22
			default:
				return false
			}
		case 22:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r >= '0' && r <= '9':
				state = 24
			default:
				return false
			}
		case 24:
			switch {
			case r == ':':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '0' && r <= '9':
				state = 26
			default:
				return false
			}
		case 26:
			switch {
			case r >= '0' && r <= '9':
				state = 27
			default:
				return false
			}
		case 27:
			switch {
			case r == ':':
				state = 28
			default:
				return false
			}
		case 28:
			switch {
			case r >= '0' && r <= '9':
				state = 29
			default:
				return false
			}
		case 29:
			switch {
			case r >= '0' && r <= '9':
				state = 30
			default:
				return false
			}
		case 30:
			switch {
			case r == ':':
				state = 31
			default:
				return false
			}
		case 31:
			switch {
			case r >= '0' && r <= '9':
				state = 32
			default:
				return false
			}
		case 32:
			switch {
			case r >= '0' && r <= '9':
				state = 33
			default:
				return false
			}
		case 33:
			switch {
			case r == ' ':
				state = 34
			default:
				return false
			}
		case 34:
			switch {
			case r == '+':
				state = 35
			case r == '-':
				state = 35
			default:
				return false
			}
		case 35:
			switch {
			case r >= '0' && r <= '9':
				state = 36
			default:
				return false
			}
		case 36:
			switch {
			case r >= '0' && r <= '9':
				state = 37
			default:
				return false
			}
		case 37:
			switch {
			case r >= '0' && r <= '9':
				state = 38
			default:
				return false
			}
		case 38:
			switch {
			case r >= '0' && r <= '9':
				state = 39
			default:
				return false
			}
		case 39:
			switch {
			case r == ']':
				state = 40
			default:
				return false
			}
		case 40:
			switch {
			case r == ' ':
				state = 41
			default:
				return false
			}
		case 41:
			switch {
			case r == '"':
				state = 42
			default:
				return false
			}
		case 42:
			switch {
			case r >= 'A' && r <= 'Z':
				state = 43
			default:
				return false
			}
		case 43:
			switch {
			case r == ' ':
				state = 44
			case r >= 'A' && r <= 'Z':
				state = 43
			default:
				return false
			}
		case 44:
			switch {
			case r >= '\x00' && r <= '!':
				state = 45
			case r >= '#' && r <= '\U0010ffff':
				state = 45
			default:
				return false
			}
		case 45:
			switch {
			case r >= '\x00' && r <= '!':
				state = 45
			case r == '"':
				state = 46
			case r >= '#' && r <= '\U0010ffff':
				state = 45
			default:
				return false
			}
		case 46:
			switch {
			case r == ' ':
				state = 47
			default:
				return false
			}
		case 47:
			switch {
			case r >= '0' && r <= '9':
				state = 48
			default:
				return false
			}
		case 48:
			switch {
			case r >= '0' && r <= '9':
				state = 49
			default:
				return false
			}
		case 49:
			switch {
			case r >= '0' && r <= '9':
				state = 50
			default:
				return false
			}
		case 50:
			switch {
			case r == ' ':
				state = 51
			default:
				return false
			}
		case 51:
			switch {
			case r == '-':
				state = 52
			case r >= '0' && r <= '9':
				state = 53
			default:
				return false
			}
		case 52:
			switch {
			default:
				return false
			}
		case 53:
			switch {
			case r >= '0' && r <= '9':
				state = 53
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 52, 53:
		return true
	default:
		return false
	}
}
