// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\d{9,10}\.\d{3}\s+\d+\s\S+\s\w+/\d{3}\s\d+\s\w+\s\S+\s\S+\s\w+/([\d\.]+|-)\s.*$`

package matchers

import "unicode/utf8"

// MatchSquidAccess reports whether input fully matches the regex `^\d{9,10}\.\d{3}\s+\d+\s\S+\s\w+/\d{3}\s\d+\s\w+\s\S+\s\S+\s\w+/([\d\.]+|-)\s.*$`.
func MatchSquidAccess(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '0' && r <= '9':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '0' && r <= '9':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '0' && r <= '9':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r == '.':
				state = 10
			case r >= '0' && r <= '9':
				state = 11
			default:
				return false
			}
		case 10:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			default:
				return false
			}
		case 11:
			switch {
			case r == '.':
				state = 10
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			case r >= '0' && r <= '9':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\t' && r <= '\n':
				state = 17
			case r >= '\f' && r <= '\r':
				state = 17
			case r == ' ':
				state = 17
			case r >= '0' && r <= '9':
				state = 16
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 18
			case r == '\v':
				state = 18
			case r >= '\x0e' && r <= '\x1f':
				state = 18
			case r >= '!' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 18
			case r >= '\t' && r <= '\n':
				state = 19
			case r == '\v':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 19
			case r >= '\x0e' && r <= '\x1f':
				state = 18
			case r == ' ':
				state = 19
			case r >= '!' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 19:
			switch {
			case r >= '0' && r <= '9':
				state = 20
			case r >= 'A' && r <= 'Z':
				state = 20
			case r == '_':
				state = 20
			case r >= 'a' && r <= 'z':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r == '/':
				state = 21
			case r >= '0' && r <= '9':
				state = 20
			case r >= 'A' && r <= 'Z':
				state = 20
			case r == '_':
				state = 20
			case r >= 'a' && r <= 'z':
				state = 20
			default:
				return false
			}
		case 21:
			switch {
			case r >= '0' && r <= '9':
				state = 22
			default:
				return false
			}
		case 22:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r >= '0' && r <= '9':
				state = 24
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\t' && r <= '\n':
				state = 25
			case r >= '\f' && r <= '\r':
				state = 25
			case r == ' ':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '0' && r <= '9':
				state = 26
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\t' && r <= '\n':
				state = 27
			case r >= '\f' && r <= '\r':
				state = 27
			case r == ' ':
				state = 27
			case r >= '0' && r <= '9':
				state = 26
			default:
				return false
			}
		case 27:
			switch {
			case r >= '0' && r <= '9':
				state = 28
			case r >= 'A' && r <= 'Z':
				state = 28
			case r == '_':
				state = 28
			case r >= 'a' && r <= 'z':
				state = 28
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\t' && r <= '\n':
				state = 29
			case r >= '\f' && r <= '\r':
				state = 29
			case r == ' ':
				state = 29
			case r >= '0' && r <= '9':
				state = 28
			case r >= 'A' && r <= 'Z':
				state = 28
			case r == '_':
				state = 28
			case r >= 'a' && r <= 'z':
				state = 28
			default:
				return false
			}
		case 29:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 30
			case r == '\v':
				state = 30
			case r >= '\x0e' && r <= '\x1f':
				state = 30
			case r >= '!' && r <= '\U0010ffff':
				state = 30
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 30
			case r >= '\t' && r <= '\n':
				state = 31
			case r == '\v':
				state = 30
			case r >= '\f' && r <= '\r':
				state = 31
			case r >= '\x0e' && r <= '\x1f':
				state = 30
			case r == ' ':
				state = 31
			case r >= '!' && r <= '\U0010ffff':
				state = 30
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 32
			case r == '\v':
				state = 32
			case r >= '\x0e' && r <= '\x1f':
				state = 32
			case r >= '!' && r <= '\U0010ffff':
				state = 32
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 32
			case r >= '\t' && r <= '\n':
				state = 33
			case r == '\v':
				state = 32
			case r >= '\f' && r <= '\r':
				state = 33
			case r >= '\x0e' && r <= '\x1f':
				state = 32
			case r == ' ':
				state = 33
			case r >= '!' && r <= '\U0010ffff':
				state = 32
			default:
				return false
			}
		case 33:
			switch {
			case r >= '0' && r <= '9':
				state = 34
			case r >= 'A' && r <= 'Z':
				state = 34
			case r == '_':
				state = 34
			case r >= 'a' && r <= 'z':
				state = 34
			default:
				return false
			}
		case 34:
			switch {
			case r == '/':
				state = 35
			case r >= '0' && r <= '9':
				state = 34
			case r >= 'A' && r <= 'Z':
				state = 34
			case r == '_':
				state = 34
			case r >= 'a' && r <= 'z':
				state = 34
			default:
				return false
			}
		case 35:
			switch {
			case r == '-':
				state = 36
			case r == '.':
				state = 37
			case r >= '0' && r <= '9':
				state = 37
			default:
				return false
			}
		case 36:
			switch {
			case r >= '\t' && r <= '\n':
				state = 38
			case r >= '\f' && r <= '\r':
				state = 38
			case r == ' ':
				state = 38
			default:
				return false
			}
		case 37:
			switch {
			case r >= '\t' && r <= '\n':
				state = 38
			case r >= '\f' && r <= '\r':
				state = 38
			case r == ' ':
				state = 38
			case r == '.':
				state = 37
			case r >= '0' && r <= '9':
				state = 37
			default:
				return false
			}
		case 38:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 38
			case r >= '\v' && r <= '\U0010ffff':
				state = 38
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 38
}
