// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[\d\.]+\s\w+\s-?[\dA-F]+\s+\S+\s[\dA-F]+\s+(\d{3}|\?)\s+(-?[\d\?]+)\s+(-?[\d\?]+)\s+(-?[\d\?]+)\s\S+\s(-?[\d|\?]+)/(-?[\d|\?]+)\s\S+\s.*$`

package matchers

import "unicode/utf8"

// MatchSquidStore reports whether input fully matches the regex `^[\d\.]+\s\w+\s-?[\dA-F]+\s+\S+\s[\dA-F]+\s+(\d{3}|\?)\s+(-?[\d\?]+)\s+(-?[\d\?]+)\s+(-?[\d\?]+)\s\S+\s(-?[\d|\?]+)/(-?[\d|\?]+)\s\S+\s.*$`.
func MatchSquidStore(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\t' && r <= '\n':
				state = 2
			case r >= '\f' && r <= '\r':
				state = 2
			case r == ' ':
				state = 2
			case r == '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 3
			case r == '_':
				state = 3
			case r >= 'a' && r <= 'z':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\t' && r <= '\n':
				state = 4
			case r >= '\f' && r <= '\r':
				state = 4
			case r == ' ':
				state = 4
			case r >= '0' && r <= '9':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 3
			case r == '_':
				state = 3
			case r >= 'a' && r <= 'z':
				state = 3
			default:
				return false
			}
		case 4:
			switch {
			case r == '-':
				state = 5
			case r >= '0' && r <= '9':
				state = 6
			case r >= 'A' && r <= 'F':
				state = 6
			default:
				return false
			}
		case 5:
			switch {
			case r >= '0' && r <= '9':
				state = 6
			case r >= 'A' && r <= 'F':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\t' && r <= '\n':
				state = 7
			case r >= '\f' && r <= '\r':
				state = 7
			case r == ' ':
				state = 7
			case r >= '0' && r <= '9':
				state = 6
			case r >= 'A' && r <= 'F':
				state = 6
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 8
			case r >= '\t' && r <= '\n':
				state = 7
			case r == '\v':
				state = 8
			case r >= '\f' && r <= '\r':
				state = 7
			case r >= '\x0e' && r <= '\x1f':
				state = 8
			case r == ' ':
				state = 7
			case r >= '!' && r <= '\U0010ffff':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 8
			case r >= '\t' && r <= '\n':
				state = 9
			case r == '\v':
				state = 8
			case r >= '\f' && r <= '\r':
				state = 9
			case r >= '\x0e' && r <= '\x1f':
				state = 8
			case r == ' ':
				state = 9
			case r >= '!' && r <= '\U0010ffff':
				state = 8
			default:
				return false
			}
		case 9:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			case r >= 'A' && r <= 'F':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\t' && r <= '\n':
				state = 11
			case r >= '\f' && r <= '\r':
				state = 11
			case r == ' ':
				state = 11
			case r >= '0' && r <= '9':
				state = 10
			case r >= 'A' && r <= 'F':
				state = 10
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\t' && r <= '\n':
				state = 11
			case r >= '\f' && r <= '\r':
				state = 11
			case r == ' ':
				state = 11
			case r >= '0' && r <= '9':
				state = 12
			case r == '?':
				state = 13
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 13
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			case r == '-':
				state = 16
			case r >= '0' && r <= '9':
				state = 17
			case r == '?':
				state = 17
			default:
				return false
			}
		case 16:
			switch {
			case r >= '0' && r <= '9':
				state = 17
			case r == '?':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\t' && r <= '\n':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 18
			case r == ' ':
				state = 18
			case r >= '0' && r <= '9':
				state = 17
			case r == '?':
				state = 17
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\t' && r <= '\n':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 18
			case r == ' ':
				state = 18
			case r == '-':
				state = 19
			case r >= '0' && r <= '9':
				state = 20
			case r == '?':
				state = 20
			default:
				return false
			}
		case 19:
			switch {
			case r >= '0' && r <= '9':
				state = 20
			case r == '?':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\t' && r <= '\n':
				state = 21
			case r >= '\f' && r <= '\r':
				state = 21
			case r == ' ':
				state = 21
			case r >= '0' && r <= '9':
				state = 20
			case r == '?':
				state = 20
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\t' && r <= '\n':
				state = 21
			case r >= '\f' && r <= '\r':
				state = 21
			case r == ' ':
				state = 21
			case r == '-':
				state = 22
			case r >= '0' && r <= '9':
				state = 23
			case r == '?':
				state = 23
			default:
				return false
			}
		case 22:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			case r == '?':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r >= '\t' && r <= '\n':
				state = 24
			case r >= '\f' && r <= '\r':
				state = 24
			case r == ' ':
				state = 24
			case r >= '0' && r <= '9':
				state = 23
			case r == '?':
				state = 23
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 25
			case r == '\v':
				state = 25
			case r >= '\x0e' && r <= '\x1f':
				state = 25
			case r >= '!' && r <= '\U0010ffff':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 25
			case r >= '\t' && r <= '\n':
				state = 26
			case r == '\v':
				state = 25
			case r >= '\f' && r <= '\r':
				state = 26
			case r >= '\x0e' && r <= '\x1f':
				state = 25
			case r == ' ':
				state = 26
			case r >= '!' && r <= '\U0010ffff':
				state = 25
			default:
				return false
			}
		case 26:
			switch {
			case r == '-':
				state = 27
			case r >= '0' && r <= '9':
				state = 28
			case r == '?':
				state = 28
			case r == '|':
				state = 28
			default:
				return false
			}
		case 27:
			switch {
			case r >= '0' && r <= '9':
				state = 28
			case r == '?':
				state = 28
			case r == '|':
				state = 28
			default:
				return false
			}
		case 28:
			switch {
			case r == '/':
				state = 29
			case r >= '0' && r <= '9':
				state = 28
			case r == '?':
				state = 28
			case r == '|':
				state = 28
			default:
				return false
			}
		case 29:
			switch {
			case r == '-':
				state = 30
			case r >= '0' && r <= '9':
				state = 31
			case r == '?':
				state = 31
			case r == '|':
				state = 31
			default:
				return false
			}
		case 30:
			switch {
			case r >= '0' && r <= '9':
				state = 31
			case r == '?':
				state = 31
			case r == '|':
				state = 31
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\t' && r <= '\n':
				state = 32
			case r >= '\f' && r <= '\r':
				state = 32
			case r == ' ':
				state = 32
			case r >= '0' && r <= '9':
				state = 31
			case r == '?':
				state = 31
			case r == '|':
				state = 31
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 33
			case r == '\v':
				state = 33
			case r >= '\x0e' && r <= '\x1f':
				state = 33
			case r >= '!' && r <= '\U0010ffff':
				state = 33
			default:
				return false
			}
		case 33:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 33
			case r >= '\t' && r <= '\n':
				state = 34
			case r == '\v':
				state = 33
			case r >= '\f' && r <= '\r':
				state = 34
			case r >= '\x0e' && r <= '\x1f':
				state = 33
			case r == ' ':
				state = 34
			case r >= '!' && r <= '\U0010ffff':
				state = 33
			default:
				return false
			}
		case 34:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 34
			case r >= '\v' && r <= '\U0010ffff':
				state = 34
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 34
}
