// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\d{4}/\d{2}/\d{2}\s(\d{2}:){2}\d{2}\|\s.*$`

package matchers

import "unicode/utf8"

// MatchSquidCache reports whether input fully matches the regex `^\d{4}/\d{2}/\d{2}\s(\d{2}:){2}\d{2}\|\s.*$`.
func MatchSquidCache(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r == '/':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '0' && r <= '9':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r == '/':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r >= '0' && r <= '9':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\t' && r <= '\n':
				state = 11
			case r >= '\f' && r <= '\r':
				state = 11
			case r == ' ':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r == ':':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r >= '0' && r <= '9':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r == ':':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '0' && r <= '9':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r >= '0' && r <= '9':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r == '|':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\t' && r <= '\n':
				state = 21
			case r >= '\f' && r <= '\r':
				state = 21
			case r == ' ':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 21
			case r >= '\v' && r <= '\U0010ffff':
				state = 21
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 21
}
