// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\S*\s{1,2}\d{1,2}\s\d\d:\d\d:\d\d\s\S+\s+\S+:?\s.*$`

package matchers

import "unicode/utf8"

// MatchSyslog reports whether input fully matches the regex `^\S*\s{1,2}\d{1,2}\s\d\d:\d\d:\d\d\s\S+\s+\S+:?\s.*$`.
func MatchSyslog(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\t' && r <= '\n':
				state = 3
			case r >= '\f' && r <= '\r':
				state = 3
			case r == ' ':
				state = 3
			case r >= '0' && r <= '9':
				state = 4
			default:
				return false
			}
		case 3:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\t' && r <= '\n':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 5
			case r == ' ':
				state = 5
			case r >= '0' && r <= '9':
				state = 6
			default:
				return false
			}
		case 5:
			switch {
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\t' && r <= '\n':
				state = 5
			case r >= '\f' && r <= '\r':
				state = 5
			case r == ' ':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r == ':':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r >= '0' && r <= '9':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '0' && r <= '9':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r == ':':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 16
			case r == '\v':
				state = 16
			case r >= '\x0e' && r <= '\x1f':
				state = 16
			case r >= '!' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 16
			case r >= '\t' && r <= '\n':
				state = 17
			case r == '\v':
				state = 16
			case r >= '\f' && r <= '\r':
				state = 17
			case r >= '\x0e' && r <= '\x1f':
				state = 16
			case r == ' ':
				state = 17
			case r >= '!' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 18
			case r >= '\t' && r <= '\n':
				state = 17
			case r == '\v':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 17
			case r >= '\x0e' && r <= '\x1f':
				state = 18
			case r == ' ':
				state = 17
			case r >= '!' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 18
			case r >= '\t' && r <= '\n':
				state = 19
			case r == '\v':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 19
			case r >= '\x0e' && r <= '\x1f':
				state = 18
			case r == ' ':
				state = 19
			case r >= '!' && r <= '9':
				state = 18
			case r == ':':
				state = 18
			case r >= ';' && r <= '\U0010ffff':
				state = 18
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 19
			case r >= '\v' && r <= '\U0010ffff':
				state = 19
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 19
}
