// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^.*(IN|OUT|MAC|TTL|SRC|TOS|PREC|SPT)=.*$`

package matchers

import "unicode/utf8"

// MatchUlogd reports whether input fully matches the regex `^.*(IN|OUT|MAC|TTL|SRC|TOS|PREC|SPT)=.*$`.
func MatchUlogd(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 8
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '@':
				state = 1
			case r == 'A':
				state = 9
			case r >= 'B' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r == 'U':
				state = 10
			case r >= 'V' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r == 'Q':
				state = 1
			case r == 'R':
				state = 11
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 12
			case r == 'Q':
				state = 1
			case r == 'R':
				state = 13
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 14
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 15
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '<':
				state = 1
			case r == '=':
				state = 16
			case r >= '>' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'B':
				state = 1
			case r == 'C':
				state = 8
			case r >= 'D' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 17
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'D':
				state = 1
			case r == 'E':
				state = 18
			case r >= 'F' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 12:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r == 'Q':
				state = 1
			case r == 'R':
				state = 11
			case r == 'S':
				state = 6
			case r == 'T':
				state = 17
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 13:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'B':
				state = 1
			case r == 'C':
				state = 8
			case r >= 'D' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 19
			case r == 'T':
				state = 7
			case r == 'U':
				state = 10
			case r >= 'V' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'K':
				state = 1
			case r == 'L':
				state = 8
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 14
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 15
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '<':
				state = 1
			case r == '=':
				state = 16
			case r >= '>' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 14
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 15
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= 'B':
				state = 1
			case r == 'C':
				state = 8
			case r >= 'D' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 5
			case r >= 'Q' && r <= 'R':
				state = 1
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 19:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '<':
				state = 1
			case r == '=':
				state = 16
			case r >= '>' && r <= 'H':
				state = 1
			case r == 'I':
				state = 2
			case r >= 'J' && r <= 'L':
				state = 1
			case r == 'M':
				state = 3
			case r == 'N':
				state = 1
			case r == 'O':
				state = 4
			case r == 'P':
				state = 12
			case r == 'Q':
				state = 1
			case r == 'R':
				state = 13
			case r == 'S':
				state = 6
			case r == 'T':
				state = 7
			case r >= 'U' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 20:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 26
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 21:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= '@':
				state = 16
			case r == 'A':
				state = 27
			case r >= 'B' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 22:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r == 'U':
				state = 28
			case r >= 'V' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 23:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r == 'Q':
				state = 16
			case r == 'R':
				state = 29
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 30
			case r == 'Q':
				state = 16
			case r == 'R':
				state = 31
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 25:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 32
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 33
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= '<':
				state = 16
			case r == '=':
				state = 16
			case r >= '>' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 27:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'B':
				state = 16
			case r == 'C':
				state = 26
			case r >= 'D' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 34
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 29:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'D':
				state = 16
			case r == 'E':
				state = 35
			case r >= 'F' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r == 'Q':
				state = 16
			case r == 'R':
				state = 29
			case r == 'S':
				state = 24
			case r == 'T':
				state = 34
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'B':
				state = 16
			case r == 'C':
				state = 26
			case r >= 'D' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 36
			case r == 'T':
				state = 25
			case r == 'U':
				state = 28
			case r >= 'V' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 33:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'K':
				state = 16
			case r == 'L':
				state = 26
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 32
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 33
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 34:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= '<':
				state = 16
			case r == '=':
				state = 16
			case r >= '>' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 32
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 33
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 35:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= 'B':
				state = 16
			case r == 'C':
				state = 26
			case r >= 'D' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 23
			case r >= 'Q' && r <= 'R':
				state = 16
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		case 36:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 16
			case r >= '\v' && r <= '<':
				state = 16
			case r == '=':
				state = 16
			case r >= '>' && r <= 'H':
				state = 16
			case r == 'I':
				state = 20
			case r >= 'J' && r <= 'L':
				state = 16
			case r == 'M':
				state = 21
			case r == 'N':
				state = 16
			case r == 'O':
				state = 22
			case r == 'P':
				state = 30
			case r == 'Q':
				state = 16
			case r == 'R':
				state = 31
			case r == 'S':
				state = 24
			case r == 'T':
				state = 25
			case r >= 'U' && r <= '\U0010ffff':
				state = 16
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 16, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36:
		return true
	default:
		return false
	}
}
