// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\S+\s+\S+\s+\d{1,2}\s+\d{1,2}:\d{1,2}:\d{1,2}\s+\d+\s+\[pid \d+\]\s+(\[\S+\])?\s*.*$`

package matchers

import "unicode/utf8"

// MatchVsftpd reports whether input fully matches the regex `^\S+\s+\S+\s+\d{1,2}\s+\d{1,2}:\d{1,2}:\d{1,2}\s+\d+\s+\[pid \d+\]\s+(\[\S+\])?\s*.*$`.
func MatchVsftpd(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r == '\v':
				state = 1
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r >= '!' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 3
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 3
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 3
			case r == ' ':
				state = 2
			case r >= '!' && r <= '\U0010ffff':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 3
			case r >= '\t' && r <= '\n':
				state = 4
			case r == '\v':
				state = 3
			case r >= '\f' && r <= '\r':
				state = 4
			case r >= '\x0e' && r <= '\x1f':
				state = 3
			case r == ' ':
				state = 4
			case r >= '!' && r <= '\U0010ffff':
				state = 3
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\t' && r <= '\n':
				state = 4
			case r >= '\f' && r <= '\r':
				state = 4
			case r == ' ':
				state = 4
			case r >= '0' && r <= '9':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\t' && r <= '\n':
				state = 6
			case r >= '\f' && r <= '\r':
				state = 6
			case r == ' ':
				state = 6
			case r >= '0' && r <= '9':
				state = 7
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\t' && r <= '\n':
				state = 6
			case r >= '\f' && r <= '\r':
				state = 6
			case r == ' ':
				state = 6
			case r >= '0' && r <= '9':
				state = 8
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\t' && r <= '\n':
				state = 6
			case r >= '\f' && r <= '\r':
				state = 6
			case r == ' ':
				state = 6
			default:
				return false
			}
		case 8:
			switch {
			case r >= '0' && r <= '9':
				state = 9
			case r == ':':
				state = 10
			default:
				return false
			}
		case 9:
			switch {
			case r == ':':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case r >= '0' && r <= '9':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case r >= '0' && r <= '9':
				state = 12
			case r == ':':
				state = 13
			default:
				return false
			}
		case 12:
			switch {
			case r == ':':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			case r >= '0' && r <= '9':
				state = 16
			default:
				return false
			}
		case 15:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			case r >= '0' && r <= '9':
				state = 17
			default:
				return false
			}
		case 16:
			switch {
			case r >= '\t' && r <= '\n':
				state = 15
			case r >= '\f' && r <= '\r':
				state = 15
			case r == ' ':
				state = 15
			default:
				return false
			}
		case 17:
			switch {
			case r >= '\t' && r <= '\n':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 18
			case r == ' ':
				state = 18
			case r >= '0' && r <= '9':
				state = 17
			default:
				return false
			}
		case 18:
			switch {
			case r >= '\t' && r <= '\n':
				state = 18
			case r >= '\f' && r <= '\r':
				state = 18
			case r == ' ':
				state = 18
			case r == '[':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case r == 'p':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case r == 'i':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case r == 'd':
				state = 22
			default:
				return false
			}
		case 22:
			switch {
			case r == ' ':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r >= '0' && r <= '9':
				state = 24
			default:
				return false
			}
		case 24:
			switch {
			case r >= '0' && r <= '9':
				state = 24
			case r == ']':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '\t' && r <= '\n':
				state = 26
			case r >= '\f' && r <= '\r':
				state = 26
			case r == ' ':
				state = 26
			default:
				return false
			}
		case 26:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 27
			case r == '\t':
				state = 26
			case r == '\n':
				state = 26
			case r == '\v':
				state = 27
			case r >= '\f' && r <= '\r':
				state = 26
			case r >= '\x0e' && r <= '\x1f':
				state = 27
			case r == ' ':
				state = 26
			case r >= '!' && r <= 'Z':
				state = 27
			case r == '[':
				state = 28
			case r >= '\\' && r <= '\U0010ffff':
				state = 27
			default:
				return false
			}
		case 27:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 27
			case r >= '\v' && r <= '\U0010ffff':
				state = 27
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 29
			case r == '\t':
				state = 27
			case r == '\v':
				state = 29
			case r >= '\f' && r <= '\r':
				state = 27
			case r >= '\x0e' && r <= '\x1f':
				state = 29
			case r == ' ':
				state = 27
			case r >= '!' && r <= '\U0010ffff':
				state = 29
			default:
				return false
			}
		case 29:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 29
			case r == '\t':
				state = 27
			case r == '\v':
				state = 29
			case r >= '\f' && r <= '\r':
				state = 27
			case r >= '\x0e' && r <= '\x1f':
				state = 29
			case r == ' ':
				state = 27
			case r >= '!' && r <= '\\':
				state = 29
			case r == ']':
				state = 30
			case r >= '^' && r <= '\U0010ffff':
				state = 29
			default:
				return false
			}
		case 30:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 29
			case r == '\t':
				state = 31
			case r == '\n':
				state = 31
			case r == '\v':
				state = 29
			case r >= '\f' && r <= '\r':
				state = 31
			case r >= '\x0e' && r <= '\x1f':
				state = 29
			case r == ' ':
				state = 31
			case r >= '!' && r <= '\\':
				state = 29
			case r == ']':
				state = 30
			case r >= '^' && r <= '\U0010ffff':
				state = 29
			default:
				return false
			}
		case 31:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 27
			case r == '\t':
				state = 31
			case r == '\n':
				state = 31
			case r == '\v':
				state = 27
			case r >= '\f' && r <= '\r':
				state = 31
			case r >= '\x0e' && r <= '\x1f':
				state = 27
			case r == ' ':
				state = 31
			case r >= '!' && r <= '\U0010ffff':
				state = 27
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 26, 27, 28, 29, 30, 31:
		return true
	default:
		return false
	}
}
