// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^... ... +\d{1,2} +\d{1,2}:\d{1,2}:\d{1,2} \d+ \d+ [^ ]+ \d+ \S+ (a|b) (C|U|T|_) (o|i) (a|g|r) [^ ]+ [^ ]+ (0|1) [^ ]+ (c|i).*$`

package matchers

import "unicode/utf8"

// MatchXferlog reports whether input fully matches the regex `^... ... +\d{1,2} +\d{1,2}:\d{1,2}:\d{1,2} \d+ \d+ [^ ]+ \d+ \S+ (a|b) (C|U|T|_) (o|i) (a|g|r) [^ ]+ [^ ]+ (0|1) [^ ]+ (c|i).*$`.
func MatchXferlog(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 2
			case r >= '\v' && r <= '\U0010ffff':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 3
			case r >= '\v' && r <= '\U0010ffff':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == ' ':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 7
			case r >= '\v' && r <= '\U0010ffff':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case r == ' ':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case r == ' ':
				state = 8
			case r >= '0' && r <= '9':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case r == ' ':
				state = 10
			case r >= '0' && r <= '9':
				state = 11
			default:
				return false
			}
		case 10:
			switch {
			case r == ' ':
				state = 10
			case r >= '0' && r <= '9':
				state = 12
			default:
				return false
			}
		case 11:
			switch {
			case r == ' ':
				state = 10
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 13
			case r == ':':
				state = 14
			default:
				return false
			}
		case 13:
			switch {
			case r == ':':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case r >= '0' && r <= '9':
				state = 16
			case r == ':':
				state = 17
			default:
				return false
			}
		case 16:
			switch {
			case r == ':':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case r >= '0' && r <= '9':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case r == ' ':
				state = 19
			case r >= '0' && r <= '9':
				state = 20
			default:
				return false
			}
		case 19:
			switch {
			case r >= '0' && r <= '9':
				state = 21
			default:
				return false
			}
		case 20:
			switch {
			case r == ' ':
				state = 19
			default:
				return false
			}
		case 21:
			switch {
			case r == ' ':
				state = 22
			case r >= '0' && r <= '9':
				state = 21
			default:
				return false
			}
		case 22:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case r == ' ':
				state = 24
			case r >= '0' && r <= '9':
				state = 23
			default:
				return false
			}
		case 24:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 25
			case r >= '!' && r <= '\U0010ffff':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 25
			case r == ' ':
				state = 26
			case r >= '!' && r <= '\U0010ffff':
				state = 25
			default:
				return false
			}
		case 26:
			switch {
			case r >= '0' && r <= '9':
				state = 27
			default:
				return false
			}
		case 27:
			switch {
			case r == ' ':
				state = 28
			case r >= '0' && r <= '9':
				state = 27
			default:
				return false
			}
		case 28:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 29
			case r == '\v':
				state = 29
			case r >= '\x0e' && r <= '\x1f':
				state = 29
			case r >= '!' && r <= '\U0010ffff':
				state = 29
			default:
				return false
			}
		case 29:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 29
			case r == '\v':
				state = 29
			case r >= '\x0e' && r <= '\x1f':
				state = 29
			case r == ' ':
				state = 30
			case r >= '!' && r <= '\U0010ffff':
				state = 29
			default:
				return false
			}
		case 30:
			switch {
			case r >= 'a' && r <= 'b':
				state = 31
			default:
				return false
			}
		case 31:
			switch {
			case r == ' ':
				state = 32
			default:
				return false
			}
		case 32:
			switch {
			case r == 'C':
				state = 33
			case r >= 'T' && r <= 'U':
				state = 33
			case r == '_':
				state = 33
			default:
				return false
			}
		case 33:
			switch {
			case r == ' ':
				state = 34
			default:
				return false
			}
		case 34:
			switch {
			case r == 'i':
				state = 35
			case r == 'o':
				state = 35
			default:
				return false
			}
		case 35:
			switch {
			case r == ' ':
				state = 36
			default:
				return false
			}
		case 36:
			switch {
			case r == 'a':
				state = 37
			case r == 'g':
				state = 37
			case r == 'r':
				state = 37
			default:
				return false
			}
		case 37:
			switch {
			case r == ' ':
				state = 38
			default:
				return false
			}
		case 38:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 39
			case r >= '!' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 39:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 39
			case r == ' ':
				state = 40
			case r >= '!' && r <= '\U0010ffff':
				state = 39
			default:
				return false
			}
		case 40:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 41
			case r >= '!' && r <= '\U0010ffff':
				state = 41
			default:
				return false
			}
		case 41:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 41
			case r == ' ':
				state = 42
			case r >= '!' && r <= '\U0010ffff':
				state = 41
			default:
				return false
			}
		case 42:
			switch {
			case r >= '0' && r <= '1':
				state = 43
			default:
				return false
			}
		case 43:
			switch {
			case r == ' ':
				state = 44
			default:
				return false
			}
		case 44:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 45
			case r >= '!' && r <= '\U0010ffff':
				state = 45
			default:
				return false
			}
		case 45:
			switch {
			case r >= '\x00' && r <= '\x1f':
				state = 45
			case r == ' ':
				state = 46
			case r >= '!' && r <= '\U0010ffff':
				state = 45
			default:
				return false
			}
		case 46:
			switch {
			case r == 'c':
				state = 47
			case r == 'i':
				state = 47
			default:
				return false
			}
		case 47:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 48
			case r >= '\v' && r <= '\U0010ffff':
				state = 48
			default:
				return false
			}
		case 48:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 48
			case r >= '\v' && r <= '\U0010ffff':
				state = 48
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 47, 48:
		return true
	default:
		return false
	}
}
