// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `[+-]?([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+`

package wordcolor

import "github.com/wow-look-at-my/go-regex-compiler/match"

import "unicode/utf8"

// matchDuration reports whether input fully matches the regex `[+-]?([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+`.
func matchDuration(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {

		case 0:
			switch {
			case r == '+', r == '-':
				state = 1
			case match.InRange(r, '0', '9'):
				state = 2
			default:
				return false
			}
		case 1:
			switch {
			case match.InRange(r, '0', '9'):
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r == '.':
				state = 3
			case match.InRange(r, '0', '9'):
				state = 2
			case r == 'h':
				state = 4
			case r == 'm':
				state = 5
			case r == 'n':
				state = 6
			case r == 's':
				state = 4
			case r == 'u':
				state = 7
			case r == 'µ':
				state = 8
			default:
				return false
			}
		case 3:
			switch {
			case match.InRange(r, '0', '9'):
				state = 9
			default:
				return false
			}
		case 4:
			switch {
			case match.InRange(r, '0', '9'):
				state = 2
			default:
				return false
			}
		case 5:
			switch {
			case match.InRange(r, '0', '9'):
				state = 2
			case r == 's':
				state = 4
			default:
				return false
			}
		case 6:
			switch {
			case r == 's':
				state = 4
			default:
				return false
			}
		case 7:
			switch {
			case r == 's':
				state = 4
			default:
				return false
			}
		case 8:
			switch {
			case r == 's':
				state = 4
			default:
				return false
			}
		case 9:
			switch {
			case match.InRange(r, '0', '9'):
				state = 9
			case r == 'h':
				state = 4
			case r == 'm':
				state = 5
			case r == 'n':
				state = 6
			case r == 's':
				state = 4
			case r == 'u':
				state = 7
			case r == 'µ':
				state = 8
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}

	switch state {
	case 4, 5:
		return true
	default:
		return false
	}
}
