// Code generated by go-regex-compiler. DO NOT EDIT.

package wordcolor

import "unicode/utf8"

var _ = utf8.RuneError // ensure import is used

func regPreMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '!' && r <= '"':
				state = 1
			case r >= '\'' && r <= '(':
				state = 1
			case r == ',':
				state = 1
			case r == '.':
				state = 1
			case r >= ':' && r <= '<':
				state = 1
			case r == '?':
				state = 1
			case r == '[':
				state = 1
			case r == '`':
				state = 1
			case r == '{':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= ' ':
				state = 2
			case r >= '!' && r <= '"':
				state = 1
			case r >= '#' && r <= '&':
				state = 2
			case r >= '\'' && r <= '(':
				state = 1
			case r >= ')' && r <= '+':
				state = 2
			case r == ',':
				state = 1
			case r == '-':
				state = 2
			case r == '.':
				state = 1
			case r >= '/' && r <= '9':
				state = 2
			case r >= ':' && r <= '<':
				state = 1
			case r >= '=' && r <= '>':
				state = 2
			case r == '?':
				state = 1
			case r >= '@' && r <= 'Z':
				state = 2
			case r == '[':
				state = 1
			case r >= '\\' && r <= '_':
				state = 2
			case r == '`':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 2
			case r == '{':
				state = 1
			case r >= '|' && r <= '\U0010ffff':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 2
			case r == '\v':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 2
			case r >= '!' && r <= '\U0010ffff':
				state = 2
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 2
}

// regPreFindSubmatch returns captured groups for the regex `^([`'".,!?:;(\[{<]+)([^`'".,!?:;(\[{<]\S*)$`.
// Returns nil if the input does not match.
// Index 0 is the entire match, indices 1..N are capture groups.
func regPreFindSubmatch(input string) []string {
	if !regPreMatch(input) {
		return nil
	}
	// NFA instruction types
	const (
		opRune      = 0
		opRune1     = 1
		opRuneAny   = 2
		opRuneAnyNL = 3
		opAlt       = 4
		opCapture   = 5
		opMatch     = 6
		opNop       = 7
		opFail      = 8
		opEmpty     = 9
	)

	type nfaInst struct {
		op    int
		out   int
		arg   int
		runes []rune
	}

	prog := []nfaInst{
		/* 0 */ {op: opFail, out: 0, arg: 0},
		/* 1 */ {op: opEmpty, out: 2, arg: 4},
		/* 2 */ {op: opCapture, out: 3, arg: 2},
		/* 3 */ {op: opRune, out: 4, arg: 0, runes: []rune{33, 34, 39, 40, 44, 44, 46, 46, 58, 60, 63, 63, 91, 91, 96, 96, 123, 123}},
		/* 4 */ {op: opAlt, out: 3, arg: 5},
		/* 5 */ {op: opCapture, out: 6, arg: 3},
		/* 6 */ {op: opCapture, out: 7, arg: 4},
		/* 7 */ {op: opRune, out: 9, arg: 0, runes: []rune{0, 32, 35, 38, 41, 43, 45, 45, 47, 57, 61, 62, 64, 90, 92, 95, 97, 122, 124, 1114111}},
		/* 8 */ {op: opRune, out: 9, arg: 0, runes: []rune{0, 8, 11, 11, 14, 31, 33, 1114111}},
		/* 9 */ {op: opAlt, out: 8, arg: 10},
		/* 10 */ {op: opCapture, out: 11, arg: 5},
		/* 11 */ {op: opEmpty, out: 12, arg: 8},
		/* 12 */ {op: opMatch, out: 0, arg: 0},
	}
	startPC := 1

	// Thompson NFA simulation with capture tracking
	type thread struct {
		pc   int
		caps [6]int
	}

	addThread := func(list []thread, pc int, caps [6]int, pos int) []thread {
		visited := make(map[int]bool)
		var stack []thread
		stack = append(stack, thread{pc: pc, caps: caps})
		for len(stack) > 0 {
			t := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			if t.pc < 0 || t.pc >= len(prog) || visited[t.pc] {
				continue
			}
			visited[t.pc] = true
			inst := &prog[t.pc]
			switch inst.op {
			case opAlt:
				stack = append(stack, thread{pc: inst.arg, caps: t.caps})
				stack = append(stack, thread{pc: int(inst.out), caps: t.caps})
			case opNop, opEmpty:
				stack = append(stack, thread{pc: int(inst.out), caps: t.caps})
			case opCapture:
				newCaps := t.caps
				if inst.arg < 6 {
					newCaps[inst.arg] = pos
				}
				stack = append(stack, thread{pc: int(inst.out), caps: newCaps})
			default:
				list = append(list, t)
			}
		}
		return list
	}

	runeMatch := func(inst *nfaInst, r rune) bool {
		switch inst.op {
		case opRuneAny:
			return true
		case opRuneAnyNL:
			return r != '\n'
		case opRune1:
			if len(inst.runes) > 0 && inst.runes[0] == r {
				return true
			}
			return false
		case opRune:
			for i := 0; i < len(inst.runes)-1; i += 2 {
				if r >= inst.runes[i] && r <= inst.runes[i+1] {
					return true
				}
			}
			if len(inst.runes)%2 == 1 {
				if r == inst.runes[len(inst.runes)-1] {
					return true
				}
			}
			return false
		}
		return false
	}

	var initCaps [6]int
	for i := range initCaps {
		initCaps[i] = -1
	}
	initCaps[0] = 0 // group 0 start = beginning of input

	current := addThread(nil, startPC, initCaps, 0)

	for i, r := range input {
		var next []thread
		for _, t := range current {
			inst := &prog[t.pc]
			if runeMatch(inst, r) {
				next = addThread(next, int(inst.out), t.caps, i+len(string(r)))
			}
		}
		current = next
	}

	for _, t := range current {
		if t.pc < len(prog) && prog[t.pc].op == opMatch {
			t.caps[1] = len(input) // group 0 end
			result := make([]string, 3)
			for g := 0; g < 3; g++ {
				s, e := t.caps[g*2], t.caps[g*2+1]
				if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
					result[g] = input[s:e]
				}
			}
			return result
		}
	}
	return nil
}

func regPostMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '"':
				state = 3
			case r >= '#' && r <= '&':
				state = 1
			case r == '\'':
				state = 3
			case r == '(':
				state = 1
			case r == ')':
				state = 3
			case r >= '*' && r <= '+':
				state = 1
			case r == ',':
				state = 3
			case r == '-':
				state = 1
			case r == '.':
				state = 3
			case r >= '/' && r <= '9':
				state = 1
			case r >= ':' && r <= ';':
				state = 3
			case r >= '<' && r <= '=':
				state = 1
			case r >= '>' && r <= '?':
				state = 3
			case r >= '@' && r <= '\\':
				state = 1
			case r == ']':
				state = 3
			case r >= '^' && r <= '_':
				state = 1
			case r == '`':
				state = 3
			case r >= 'a' && r <= '|':
				state = 1
			case r == '}':
				state = 3
			case r >= '~' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '"':
				state = 4
			case r >= '#' && r <= '&':
				state = 1
			case r == '\'':
				state = 4
			case r == '(':
				state = 1
			case r == ')':
				state = 4
			case r >= '*' && r <= '+':
				state = 1
			case r == ',':
				state = 4
			case r == '-':
				state = 1
			case r == '.':
				state = 4
			case r >= '/' && r <= '9':
				state = 1
			case r >= ':' && r <= ';':
				state = 4
			case r >= '<' && r <= '=':
				state = 1
			case r >= '>' && r <= '?':
				state = 4
			case r >= '@' && r <= '\\':
				state = 1
			case r == ']':
				state = 4
			case r >= '^' && r <= '_':
				state = 1
			case r == '`':
				state = 4
			case r >= 'a' && r <= '|':
				state = 1
			case r == '}':
				state = 4
			case r >= '~' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '!' && r <= '"':
				state = 5
			case r == '\'':
				state = 5
			case r == ')':
				state = 5
			case r == ',':
				state = 5
			case r == '.':
				state = 5
			case r >= ':' && r <= ';':
				state = 5
			case r >= '>' && r <= '?':
				state = 5
			case r == ']':
				state = 5
			case r == '`':
				state = 5
			case r == '}':
				state = 5
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '"':
				state = 3
			case r >= '#' && r <= '&':
				state = 1
			case r == '\'':
				state = 3
			case r == '(':
				state = 1
			case r == ')':
				state = 3
			case r >= '*' && r <= '+':
				state = 1
			case r == ',':
				state = 3
			case r == '-':
				state = 1
			case r == '.':
				state = 3
			case r >= '/' && r <= '9':
				state = 1
			case r >= ':' && r <= ';':
				state = 3
			case r >= '<' && r <= '=':
				state = 1
			case r >= '>' && r <= '?':
				state = 3
			case r >= '@' && r <= '\\':
				state = 1
			case r == ']':
				state = 3
			case r >= '^' && r <= '_':
				state = 1
			case r == '`':
				state = 3
			case r >= 'a' && r <= '|':
				state = 1
			case r == '}':
				state = 3
			case r >= '~' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 1
			case r >= '\t' && r <= '\n':
				state = 2
			case r == '\v':
				state = 1
			case r >= '\f' && r <= '\r':
				state = 2
			case r >= '\x0e' && r <= '\x1f':
				state = 1
			case r == ' ':
				state = 2
			case r >= '!' && r <= '"':
				state = 4
			case r >= '#' && r <= '&':
				state = 1
			case r == '\'':
				state = 4
			case r == '(':
				state = 1
			case r == ')':
				state = 4
			case r >= '*' && r <= '+':
				state = 1
			case r == ',':
				state = 4
			case r == '-':
				state = 1
			case r == '.':
				state = 4
			case r >= '/' && r <= '9':
				state = 1
			case r >= ':' && r <= ';':
				state = 4
			case r >= '<' && r <= '=':
				state = 1
			case r >= '>' && r <= '?':
				state = 4
			case r >= '@' && r <= '\\':
				state = 1
			case r == ']':
				state = 4
			case r >= '^' && r <= '_':
				state = 1
			case r == '`':
				state = 4
			case r >= 'a' && r <= '|':
				state = 1
			case r == '}':
				state = 4
			case r >= '~' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 5:
			switch {
			case r >= '!' && r <= '"':
				state = 5
			case r == '\'':
				state = 5
			case r == ')':
				state = 5
			case r == ',':
				state = 5
			case r == '.':
				state = 5
			case r >= ':' && r <= ';':
				state = 5
			case r >= '>' && r <= '?':
				state = 5
			case r == ']':
				state = 5
			case r == '`':
				state = 5
			case r == '}':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 4, 5:
		return true
	default:
		return false
	}
}

// regPostFindSubmatch returns captured groups for the regex `^(\S*[^`'".,!?:;)\]}>])([`'".,!?:;)\]}>]+)$`.
// Returns nil if the input does not match.
// Index 0 is the entire match, indices 1..N are capture groups.
func regPostFindSubmatch(input string) []string {
	if !regPostMatch(input) {
		return nil
	}
	// NFA instruction types
	const (
		opRune      = 0
		opRune1     = 1
		opRuneAny   = 2
		opRuneAnyNL = 3
		opAlt       = 4
		opCapture   = 5
		opMatch     = 6
		opNop       = 7
		opFail      = 8
		opEmpty     = 9
	)

	type nfaInst struct {
		op    int
		out   int
		arg   int
		runes []rune
	}

	prog := []nfaInst{
		/* 0 */ {op: opFail, out: 0, arg: 0},
		/* 1 */ {op: opEmpty, out: 2, arg: 4},
		/* 2 */ {op: opCapture, out: 4, arg: 2},
		/* 3 */ {op: opRune, out: 4, arg: 0, runes: []rune{0, 8, 11, 11, 14, 31, 33, 1114111}},
		/* 4 */ {op: opAlt, out: 3, arg: 5},
		/* 5 */ {op: opRune, out: 6, arg: 0, runes: []rune{0, 32, 35, 38, 40, 40, 42, 43, 45, 45, 47, 57, 60, 61, 64, 92, 94, 95, 97, 124, 126, 1114111}},
		/* 6 */ {op: opCapture, out: 7, arg: 3},
		/* 7 */ {op: opCapture, out: 8, arg: 4},
		/* 8 */ {op: opRune, out: 9, arg: 0, runes: []rune{33, 34, 39, 39, 41, 41, 44, 44, 46, 46, 58, 59, 62, 63, 93, 93, 96, 96, 125, 125}},
		/* 9 */ {op: opAlt, out: 8, arg: 10},
		/* 10 */ {op: opCapture, out: 11, arg: 5},
		/* 11 */ {op: opEmpty, out: 12, arg: 8},
		/* 12 */ {op: opMatch, out: 0, arg: 0},
	}
	startPC := 1

	// Thompson NFA simulation with capture tracking
	type thread struct {
		pc   int
		caps [6]int
	}

	addThread := func(list []thread, pc int, caps [6]int, pos int) []thread {
		visited := make(map[int]bool)
		var stack []thread
		stack = append(stack, thread{pc: pc, caps: caps})
		for len(stack) > 0 {
			t := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			if t.pc < 0 || t.pc >= len(prog) || visited[t.pc] {
				continue
			}
			visited[t.pc] = true
			inst := &prog[t.pc]
			switch inst.op {
			case opAlt:
				stack = append(stack, thread{pc: inst.arg, caps: t.caps})
				stack = append(stack, thread{pc: int(inst.out), caps: t.caps})
			case opNop, opEmpty:
				stack = append(stack, thread{pc: int(inst.out), caps: t.caps})
			case opCapture:
				newCaps := t.caps
				if inst.arg < 6 {
					newCaps[inst.arg] = pos
				}
				stack = append(stack, thread{pc: int(inst.out), caps: newCaps})
			default:
				list = append(list, t)
			}
		}
		return list
	}

	runeMatch := func(inst *nfaInst, r rune) bool {
		switch inst.op {
		case opRuneAny:
			return true
		case opRuneAnyNL:
			return r != '\n'
		case opRune1:
			if len(inst.runes) > 0 && inst.runes[0] == r {
				return true
			}
			return false
		case opRune:
			for i := 0; i < len(inst.runes)-1; i += 2 {
				if r >= inst.runes[i] && r <= inst.runes[i+1] {
					return true
				}
			}
			if len(inst.runes)%2 == 1 {
				if r == inst.runes[len(inst.runes)-1] {
					return true
				}
			}
			return false
		}
		return false
	}

	var initCaps [6]int
	for i := range initCaps {
		initCaps[i] = -1
	}
	initCaps[0] = 0 // group 0 start = beginning of input

	current := addThread(nil, startPC, initCaps, 0)

	for i, r := range input {
		var next []thread
		for _, t := range current {
			inst := &prog[t.pc]
			if runeMatch(inst, r) {
				next = addThread(next, int(inst.out), t.caps, i+len(string(r)))
			}
		}
		current = next
	}

	for _, t := range current {
		if t.pc < len(prog) && prog[t.pc].op == opMatch {
			t.caps[1] = len(input) // group 0 end
			result := make([]string, 3)
			for g := 0; g < 3; g++ {
				s, e := t.caps[g*2], t.caps[g*2+1]
				if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
					result[g] = input[s:e]
				}
			}
			return result
		}
	}
	return nil
}

func regHostMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 2
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'k':
				state = 5
			case c == 'l':
				state = 6
			case c >= 'm' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 1:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 9
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 3:
			switch {
			case c == ':':
				state = 10
			default:
				return false
			}
		case 4:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 5:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'n':
				state = 5
			case c == 'o':
				state = 11
			case c >= 'p' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 8:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 13
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 9:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 14
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 10:
			switch {
			case c >= '0' && c <= '9':
				state = 15
			case c >= 'A' && c <= 'Z':
				state = 15
			case c == '_':
				state = 15
			case c >= 'a' && c <= 'z':
				state = 15
			default:
				return false
			}
		case 11:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'b':
				state = 5
			case c == 'c':
				state = 16
			case c >= 'd' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 12:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 17
			default:
				return false
			}
		case 13:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 19
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 14:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 15:
			switch {
			case c >= '0' && c <= '9':
				state = 15
			case c == ':':
				state = 20
			case c >= 'A' && c <= 'Z':
				state = 15
			case c == '_':
				state = 15
			case c >= 'a' && c <= 'z':
				state = 15
			default:
				return false
			}
		case 16:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c == 'a':
				state = 21
			case c >= 'b' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 17:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 23
			default:
				return false
			}
		case 18:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 24
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 19:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 25
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 20:
			switch {
			case c >= '0' && c <= '9':
				state = 26
			case c == ':':
				state = 10
			default:
				return false
			}
		case 21:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'k':
				state = 5
			case c == 'l':
				state = 27
			case c >= 'm' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 22:
			switch {
			case c >= '0' && c <= '9':
				state = 26
			default:
				return false
			}
		case 23:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 24:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 29
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 25:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 26:
			switch {
			case c >= '0' && c <= '9':
				state = 30
			default:
				return false
			}
		case 27:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'g':
				state = 5
			case c == 'h':
				state = 31
			case c >= 'i' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 28:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 32
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 29:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 33
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 30:
			switch {
			case c >= '0' && c <= '9':
				state = 34
			default:
				return false
			}
		case 31:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'n':
				state = 5
			case c == 'o':
				state = 35
			case c >= 'p' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 32:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 36
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 33:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 34:
			switch {
			case c >= '0' && c <= '9':
				state = 37
			default:
				return false
			}
		case 35:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'r':
				state = 5
			case c == 's':
				state = 38
			case c >= 't' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 36:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 39
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 37:
			switch {
			case c >= '0' && c <= '9':
				state = 40
			default:
				return false
			}
		case 38:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 's':
				state = 5
			case c == 't':
				state = 41
			case c >= 'u' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 39:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 40:
			switch {
			default:
				return false
			}
		case 41:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 20
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
	}
	switch state {
	case 15, 17, 23, 26, 30, 32, 34, 36, 37, 39, 40, 41:
		return true
	default:
		return false
	}
}

func regHostIPMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 2
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'k':
				state = 5
			case c == 'l':
				state = 6
			case c >= 'm' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 1:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 2:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 9
			case c >= '0' && c <= '9':
				state = 10
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 3:
			switch {
			case c == ':':
				state = 12
			default:
				goto done
			}
		case 4:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				goto done
			}
		case 5:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 6:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'n':
				state = 5
			case c == 'o':
				state = 13
			case c >= 'p' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 7:
			switch {
			case c >= '0' && c <= '9':
				state = 14
			default:
				goto done
			}
		case 8:
			switch {
			default:
				goto done
			}
		case 9:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 15
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 10:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 9
			case c >= '0' && c <= '9':
				state = 16
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 11:
			switch {
			case c >= '0' && c <= '9':
				state = 14
			case c == ':':
				state = 12
			default:
				goto done
			}
		case 12:
			switch {
			case c >= '0' && c <= '9':
				state = 17
			case c >= 'A' && c <= 'Z':
				state = 17
			case c == '_':
				state = 17
			case c >= 'a' && c <= 'z':
				state = 17
			default:
				goto done
			}
		case 13:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'b':
				state = 5
			case c == 'c':
				state = 18
			case c >= 'd' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 14:
			switch {
			case c >= '0' && c <= '9':
				state = 19
			case c == '[':
				state = 8
			default:
				goto done
			}
		case 15:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 20
			case c >= '0' && c <= '9':
				state = 21
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 16:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 9
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 17:
			switch {
			case c >= '0' && c <= '9':
				state = 17
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 17
			case c == '[':
				state = 8
			case c == '_':
				state = 17
			case c >= 'a' && c <= 'z':
				state = 17
			default:
				goto done
			}
		case 18:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c == 'a':
				state = 22
			case c >= 'b' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 19:
			switch {
			case c >= '0' && c <= '9':
				state = 23
			case c == '[':
				state = 8
			default:
				goto done
			}
		case 20:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 24
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 21:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 20
			case c >= '0' && c <= '9':
				state = 25
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 22:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'k':
				state = 5
			case c == 'l':
				state = 26
			case c >= 'm' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 23:
			switch {
			case c >= '0' && c <= '9':
				state = 27
			case c == '[':
				state = 8
			default:
				goto done
			}
		case 24:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 29
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 25:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 20
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 26:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'g':
				state = 5
			case c == 'h':
				state = 30
			case c >= 'i' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 27:
			switch {
			case c >= '0' && c <= '9':
				state = 31
			case c == '[':
				state = 8
			default:
				goto done
			}
		case 28:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 32
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 29:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 33
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 30:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'n':
				state = 5
			case c == 'o':
				state = 34
			case c >= 'p' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 31:
			switch {
			case c == '[':
				state = 8
			default:
				goto done
			}
		case 32:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 35
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 33:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 34:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'r':
				state = 5
			case c == 's':
				state = 36
			case c >= 't' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 35:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 37
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 36:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 's':
				state = 5
			case c == 't':
				state = 38
			case c >= 'u' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 37:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 7
			case c == '[':
				state = 8
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 38:
			switch {
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 11
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '[':
				state = 8
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		default:
			goto done
		}
	}
done:
	return state == 8
}

func regMACMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			case c >= 'a' && c <= 'f':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case c >= '0' && c <= '9':
				state = 2
			case c >= 'a' && c <= 'f':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c == ':':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'f':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case c >= '0' && c <= '9':
				state = 5
			case c >= 'a' && c <= 'f':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case c == ':':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case c >= '0' && c <= '9':
				state = 7
			case c >= 'a' && c <= 'f':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case c >= '0' && c <= '9':
				state = 8
			case c >= 'a' && c <= 'f':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case c == ':':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case c >= '0' && c <= '9':
				state = 10
			case c >= 'a' && c <= 'f':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case c >= '0' && c <= '9':
				state = 11
			case c >= 'a' && c <= 'f':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case c == ':':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case c >= '0' && c <= '9':
				state = 13
			case c >= 'a' && c <= 'f':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case c >= '0' && c <= '9':
				state = 14
			case c >= 'a' && c <= 'f':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case c == ':':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case c >= '0' && c <= '9':
				state = 16
			case c >= 'a' && c <= 'f':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case c >= '0' && c <= '9':
				state = 17
			case c >= 'a' && c <= 'f':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 17
}

func regEmailMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '+':
				state = 1
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == '=':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 1:
			switch {
			case c == '+':
				state = 1
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == '=':
				state = 1
			case c == '@':
				state = 2
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 2:
			switch {
			case c >= '-' && c <= '.':
				state = 3
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 3
			default:
				goto done
			}
		case 3:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 3
			default:
				goto done
			}
		case 4:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 5:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 6
			default:
				goto done
			}
		case 6:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 7
			default:
				goto done
			}
		case 7:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 8
			default:
				goto done
			}
		case 8:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 3
			default:
				goto done
			}
		default:
			goto done
		}
	}
done:
	switch state {
	case 6, 7, 8:
		return true
	default:
		return false
	}
}

func regEmail2Match(input string) bool {
	for start := 0; start <= len(input); start++ {
		state := 0
		matched := false
		for i := start; i < len(input); i++ {
			c := input[i]
			dead := false
			switch state {
			case 0:
				switch {
				case c == '.':
					state = 1
				default:
					dead = true
				}
			case 1:
				switch {
				case c >= 'a' && c <= 'z':
					state = 2
				default:
					dead = true
				}
			case 2:
				switch {
				case c >= 'a' && c <= 'z':
					state = 3
				default:
					dead = true
				}
			case 3:
				switch {
				case c == '.':
					state = 1
				case c >= 'a' && c <= 'z':
					state = 4
				default:
					dead = true
				}
			case 4:
				switch {
				case c == '.':
					state = 1
				case c >= 'a' && c <= 'z':
					state = 5
				default:
					dead = true
				}
			case 5:
				switch {
				case c == '.':
					state = 1
				default:
					dead = true
				}
			default:
				dead = true
			}
			if dead {
				break
			}
			switch state {
			case 3, 4, 5:
				matched = true
			default:
			}
		}
		if matched {
			return true
		}
	}
	return false
}

func regMsgIDMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '$':
				state = 1
			case c == '+':
				state = 1
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == '=':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 1:
			switch {
			case c == '$':
				state = 1
			case c == '+':
				state = 1
			case c >= '-' && c <= '.':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == '=':
				state = 1
			case c == '@':
				state = 2
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				goto done
			}
		case 2:
			switch {
			case c >= '-' && c <= '.':
				state = 3
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 3
			default:
				goto done
			}
		case 3:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 3
			default:
				goto done
			}
		case 4:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		case 5:
			switch {
			case c == '-':
				state = 3
			case c == '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				goto done
			}
		default:
			goto done
		}
	}
done:
	return state == 5
}

func regURIMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			case r >= 'A' && r <= 'Z':
				state = 1
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			case r >= 'A' && r <= 'Z':
				state = 2
			case r == '_':
				state = 2
			case r >= 'a' && r <= 'z':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			case r == ':':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 2
			case r == '_':
				state = 2
			case r >= 'a' && r <= 'z':
				state = 2
			default:
				return false
			}
		case 3:
			switch {
			case r == '/':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r == '/':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 6
			case r == '\v':
				state = 6
			case r >= '\x0e' && r <= '\x1f':
				state = 6
			case r >= '!' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 6
			case r == '\v':
				state = 6
			case r >= '\x0e' && r <= '\x1f':
				state = 6
			case r >= '!' && r <= '.':
				state = 6
			case r == '/':
				state = 6
			case r >= '0' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 6
}

func regSizeMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			default:
				goto done
			}
		case 1:
			switch {
			case c == '.':
				state = 2
			case c >= '0' && c <= '9':
				state = 1
			case c == 'g':
				state = 3
			case c == 'k':
				state = 3
			case c == 'm':
				state = 3
			case c == 't':
				state = 3
			default:
				goto done
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			default:
				goto done
			}
		case 3:
			switch {
			case c == 'b':
				state = 5
			case c == 'i':
				state = 6
			case c == 'y':
				state = 7
			default:
				goto done
			}
		case 4:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c == 'g':
				state = 3
			case c == 'k':
				state = 3
			case c == 'm':
				state = 3
			case c == 't':
				state = 3
			default:
				goto done
			}
		case 5:
			switch {
			case c == 'y':
				state = 7
			default:
				goto done
			}
		case 6:
			switch {
			case c == 'b':
				state = 5
			case c == 'y':
				state = 7
			default:
				goto done
			}
		case 7:
			switch {
			case c == 't':
				state = 8
			default:
				goto done
			}
		case 8:
			switch {
			case c == 'e':
				state = 9
			default:
				goto done
			}
		case 9:
			switch {
			case c == 's':
				state = 10
			default:
				goto done
			}
		case 10:
			switch {
			default:
				goto done
			}
		default:
			goto done
		}
	}
done:
	switch state {
	case 3, 5, 6, 9, 10:
		return true
	default:
		return false
	}
}

func regVerMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			case c == 'v':
				state = 2
			default:
				return false
			}
		case 1:
			switch {
			case c == '.':
				state = 3
			case c >= '0' && c <= '9':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case c == '.':
				state = 5
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 5:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 4
}

func regTimeMatch(input string) bool {
	for start := 0; start <= len(input); start++ {
		state := 0
		matched := false
		for i := start; i < len(input); i++ {
			c := input[i]
			dead := false
			switch state {
			case 0:
				switch {
				case c >= '0' && c <= '9':
					state = 1
				default:
					dead = true
				}
			case 1:
				switch {
				case c >= '0' && c <= '9':
					state = 2
				case c == ':':
					state = 3
				default:
					dead = true
				}
			case 2:
				switch {
				case c == ':':
					state = 3
				default:
					dead = true
				}
			case 3:
				switch {
				case c >= '0' && c <= '9':
					state = 4
				default:
					dead = true
				}
			case 4:
				switch {
				case c >= '0' && c <= '9':
					state = 5
				case c == ':':
					state = 6
				default:
					dead = true
				}
			case 5:
				switch {
				case c == ':':
					state = 6
				default:
					dead = true
				}
			case 6:
				switch {
				case c >= '0' && c <= '9':
					state = 7
				default:
					dead = true
				}
			case 7:
				switch {
				case c >= '0' && c <= '9':
					state = 8
				default:
					dead = true
				}
			case 8:
				switch {
				default:
					dead = true
				}
			default:
				dead = true
			}
			if dead {
				break
			}
			switch state {
			case 4, 5, 7, 8:
				matched = true
			default:
			}
		}
		if matched {
			return true
		}
	}
	return false
}

func regAddrMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '0':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case c == 'x':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 3
			case c >= 'a' && c <= 'f':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case c >= '0' && c <= '9':
				state = 3
			case c >= 'a' && c <= 'f':
				state = 3
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 3
}

func regNumMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '+':
				state = 1
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 2
			default:
				return false
			}
		case 1:
			switch {
			case c >= '0' && c <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 2
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 2
}

func regSigMatch(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == 's':
				state = 1
			default:
				goto done
			}
		case 1:
			switch {
			case c == 'i':
				state = 2
			default:
				goto done
			}
		case 2:
			switch {
			case c == 'g':
				state = 3
			default:
				goto done
			}
		case 3:
			switch {
			case c == 'a':
				state = 4
			case c == 'b':
				state = 5
			case c == 'c':
				state = 6
			case c == 'e':
				state = 7
			case c == 'f':
				state = 8
			case c == 'h':
				state = 9
			case c == 'i':
				state = 10
			case c == 'k':
				state = 11
			case c == 'l':
				state = 12
			case c == 'p':
				state = 13
			case c == 'q':
				state = 14
			case c == 's':
				state = 15
			case c == 't':
				state = 16
			case c == 'u':
				state = 17
			case c == 'v':
				state = 18
			case c == 'w':
				state = 19
			case c == 'x':
				state = 20
			default:
				goto done
			}
		case 4:
			switch {
			case c == 'b':
				state = 21
			case c == 'l':
				state = 22
			default:
				goto done
			}
		case 5:
			switch {
			case c == 'u':
				state = 23
			default:
				goto done
			}
		case 6:
			switch {
			case c == 'h':
				state = 24
			case c == 'l':
				state = 25
			case c == 'o':
				state = 26
			default:
				goto done
			}
		case 7:
			switch {
			case c == 'm':
				state = 27
			default:
				goto done
			}
		case 8:
			switch {
			case c == 'p':
				state = 28
			default:
				goto done
			}
		case 9:
			switch {
			case c == 'u':
				state = 29
			default:
				goto done
			}
		case 10:
			switch {
			case c == 'l':
				state = 30
			case c == 'n':
				state = 31
			case c == 'o':
				state = 32
			default:
				goto done
			}
		case 11:
			switch {
			case c == 'i':
				state = 33
			default:
				goto done
			}
		case 12:
			switch {
			case c == 'o':
				state = 34
			default:
				goto done
			}
		case 13:
			switch {
			case c == 'i':
				state = 35
			case c == 'o':
				state = 36
			case c == 'r':
				state = 37
			case c == 'w':
				state = 38
			default:
				goto done
			}
		case 14:
			switch {
			case c == 'u':
				state = 39
			default:
				goto done
			}
		case 15:
			switch {
			case c == 'e':
				state = 40
			case c == 't':
				state = 41
			case c == 'y':
				state = 42
			default:
				goto done
			}
		case 16:
			switch {
			case c == 'e':
				state = 43
			case c == 'i':
				state = 44
			case c == 'o':
				state = 45
			case c == 'r':
				state = 46
			case c == 's':
				state = 47
			default:
				goto done
			}
		case 17:
			switch {
			case c == 'n':
				state = 48
			case c == 'r':
				state = 49
			case c == 's':
				state = 50
			default:
				goto done
			}
		case 18:
			switch {
			case c == 't':
				state = 51
			default:
				goto done
			}
		case 19:
			switch {
			case c == 'i':
				state = 52
			default:
				goto done
			}
		case 20:
			switch {
			case c == 'c':
				state = 53
			case c == 'f':
				state = 54
			default:
				goto done
			}
		case 21:
			switch {
			case c == 'r':
				state = 55
			default:
				goto done
			}
		case 22:
			switch {
			case c == 'r':
				state = 56
			default:
				goto done
			}
		case 23:
			switch {
			case c == 's':
				state = 57
			default:
				goto done
			}
		case 24:
			switch {
			case c == 'l':
				state = 58
			default:
				goto done
			}
		case 25:
			switch {
			case c == 'd':
				state = 57
			default:
				goto done
			}
		case 26:
			switch {
			case c == 'n':
				state = 59
			default:
				goto done
			}
		case 27:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 28:
			switch {
			case c == 'e':
				state = 57
			default:
				goto done
			}
		case 29:
			switch {
			case c == 'p':
				state = 57
			default:
				goto done
			}
		case 30:
			switch {
			case c == 'l':
				state = 57
			default:
				goto done
			}
		case 31:
			switch {
			case c == 'f':
				state = 60
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 32:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 33:
			switch {
			case c == 'l':
				state = 61
			default:
				goto done
			}
		case 34:
			switch {
			case c == 's':
				state = 62
			default:
				goto done
			}
		case 35:
			switch {
			case c == 'p':
				state = 63
			default:
				goto done
			}
		case 36:
			switch {
			case c == 'l':
				state = 64
			default:
				goto done
			}
		case 37:
			switch {
			case c == 'o':
				state = 65
			default:
				goto done
			}
		case 38:
			switch {
			case c == 'r':
				state = 57
			default:
				goto done
			}
		case 39:
			switch {
			case c == 'i':
				state = 66
			default:
				goto done
			}
		case 40:
			switch {
			case c == 'g':
				state = 67
			default:
				goto done
			}
		case 41:
			switch {
			case c == 'k':
				state = 68
			case c == 'o':
				state = 69
			default:
				goto done
			}
		case 42:
			switch {
			case c == 's':
				state = 57
			default:
				goto done
			}
		case 43:
			switch {
			case c == 'r':
				state = 70
			default:
				goto done
			}
		case 44:
			switch {
			case c == 'n':
				state = 57
			default:
				goto done
			}
		case 45:
			switch {
			case c == 'u':
				state = 71
			default:
				goto done
			}
		case 46:
			switch {
			case c == 'a':
				state = 72
			default:
				goto done
			}
		case 47:
			switch {
			case c == 't':
				state = 73
			default:
				goto done
			}
		case 48:
			switch {
			case c == 'u':
				state = 74
			default:
				goto done
			}
		case 49:
			switch {
			case c == 'g':
				state = 57
			default:
				goto done
			}
		case 50:
			switch {
			case c == 'r':
				state = 75
			default:
				goto done
			}
		case 51:
			switch {
			case c == 'a':
				state = 76
			default:
				goto done
			}
		case 52:
			switch {
			case c == 'n':
				state = 77
			default:
				goto done
			}
		case 53:
			switch {
			case c == 'p':
				state = 78
			default:
				goto done
			}
		case 54:
			switch {
			case c == 's':
				state = 79
			default:
				goto done
			}
		case 55:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 56:
			switch {
			case c == 'm':
				state = 57
			default:
				goto done
			}
		case 57:
			switch {
			default:
				goto done
			}
		case 58:
			switch {
			case c == 'd':
				state = 57
			default:
				goto done
			}
		case 59:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 60:
			switch {
			case c == 'o':
				state = 57
			default:
				goto done
			}
		case 61:
			switch {
			case c == 'l':
				state = 57
			default:
				goto done
			}
		case 62:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 63:
			switch {
			case c == 'e':
				state = 57
			default:
				goto done
			}
		case 64:
			switch {
			case c == 'l':
				state = 57
			default:
				goto done
			}
		case 65:
			switch {
			case c == 'f':
				state = 57
			default:
				goto done
			}
		case 66:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 67:
			switch {
			case c == 'v':
				state = 57
			default:
				goto done
			}
		case 68:
			switch {
			case c == 'f':
				state = 80
			default:
				goto done
			}
		case 69:
			switch {
			case c == 'p':
				state = 57
			default:
				goto done
			}
		case 70:
			switch {
			case c == 'm':
				state = 57
			default:
				goto done
			}
		case 71:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 72:
			switch {
			case c == 'p':
				state = 57
			default:
				goto done
			}
		case 73:
			switch {
			case c == 'p':
				state = 57
			default:
				goto done
			}
		case 74:
			switch {
			case c == 's':
				state = 81
			default:
				goto done
			}
		case 75:
			switch {
			case c >= '1' && c <= '2':
				state = 57
			default:
				goto done
			}
		case 76:
			switch {
			case c == 'l':
				state = 82
			default:
				goto done
			}
		case 77:
			switch {
			case c == 'c':
				state = 83
			default:
				goto done
			}
		case 78:
			switch {
			case c == 'u':
				state = 57
			default:
				goto done
			}
		case 79:
			switch {
			case c == 'z':
				state = 57
			default:
				goto done
			}
		case 80:
			switch {
			case c == 'l':
				state = 84
			default:
				goto done
			}
		case 81:
			switch {
			case c == 'e':
				state = 85
			default:
				goto done
			}
		case 82:
			switch {
			case c == 'r':
				state = 86
			default:
				goto done
			}
		case 83:
			switch {
			case c == 'h':
				state = 57
			default:
				goto done
			}
		case 84:
			switch {
			case c == 't':
				state = 57
			default:
				goto done
			}
		case 85:
			switch {
			case c == 'd':
				state = 57
			default:
				goto done
			}
		case 86:
			switch {
			case c == 'm':
				state = 57
			default:
				goto done
			}
		default:
			goto done
		}
	}
done:
	switch state {
	case 32, 57:
		return true
	default:
		return false
	}
}
