// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `[A-Za-z][A-Za-z0-9_.-]*`

package wordcolor

import "github.com/wow-look-at-my/go-regex-compiler/match"

// isSlogKey reports whether input fully matches the regex `[A-Za-z][A-Za-z0-9_.-]*`.
func isSlogKey(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, 'A', 'Z'), match.InRange(c, 'a', 'z'):
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case match.InRange(c, '-', '.'), match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'):
				state = 1
			default:
				return false
			}
		default:
			return false
		}
	}

	return state == 1
}
