// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^0x(\d|[a-f])+$`

package matchers

// MatchAddr reports whether input fully matches the regex `^0x(\d|[a-f])+$`.
func MatchAddr(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '0':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case c == 'x':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 3
			case c >= 'a' && c <= 'f':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case c >= '0' && c <= '9':
				state = 3
			case c >= 'a' && c <= 'f':
				state = 3
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 3
}
