// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^.*(\.[a-z]{2,4})+$`

package matchers

import "unicode/utf8"

// MatchEmail2 reports whether input fully matches the regex `^.*(\.[a-z]{2,4})+$`.
func MatchEmail2(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '`':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 3
			case r >= '{' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '`':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 4
			case r >= '{' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '`':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 5
			case r >= '{' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '`':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 6
			case r >= '{' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '-':
				state = 1
			case r == '.':
				state = 2
			case r >= '/' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 4, 5, 6:
		return true
	default:
		return false
	}
}
