// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^(((\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(([a-z0-9\-_\.]+)+)|(localhost)|(\w*::\w+)+)(:\d{1,5})?)\[.*$`

package matchers

import "unicode/utf8"

// MatchHostIP reports whether input fully matches the regex `^(((\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(([a-z0-9\-_\.]+)+)|(localhost)|(\w*::\w+)+)(:\d{1,5})?)\[.*$`.
func MatchHostIP(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 2
			case r == ':':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'k':
				state = 5
			case r == 'l':
				state = 6
			case r >= 'm' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 1:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 9
			case r >= '0' && r <= '9':
				state = 10
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 3:
			switch {
			case r == ':':
				state = 12
			default:
				return false
			}
		case 4:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			case r == ':':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '_':
				state = 4
			case r >= 'a' && r <= 'z':
				state = 4
			default:
				return false
			}
		case 5:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'n':
				state = 5
			case r == 'o':
				state = 13
			case r >= 'p' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 8
			case r >= '\v' && r <= '\U0010ffff':
				state = 8
			default:
				return false
			}
		case 9:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 15
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 10:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 9
			case r >= '0' && r <= '9':
				state = 16
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 11:
			switch {
			case r >= '0' && r <= '9':
				state = 14
			case r == ':':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case r >= '0' && r <= '9':
				state = 17
			case r >= 'A' && r <= 'Z':
				state = 17
			case r == '_':
				state = 17
			case r >= 'a' && r <= 'z':
				state = 17
			default:
				return false
			}
		case 13:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'b':
				state = 5
			case r == 'c':
				state = 18
			case r >= 'd' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 14:
			switch {
			case r >= '0' && r <= '9':
				state = 19
			case r == '[':
				state = 8
			default:
				return false
			}
		case 15:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 20
			case r >= '0' && r <= '9':
				state = 21
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 16:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 9
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 17:
			switch {
			case r >= '0' && r <= '9':
				state = 17
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 17
			case r == '[':
				state = 8
			case r == '_':
				state = 17
			case r >= 'a' && r <= 'z':
				state = 17
			default:
				return false
			}
		case 18:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r == 'a':
				state = 22
			case r >= 'b' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 19:
			switch {
			case r >= '0' && r <= '9':
				state = 23
			case r == '[':
				state = 8
			default:
				return false
			}
		case 20:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 24
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 21:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 20
			case r >= '0' && r <= '9':
				state = 25
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 22:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'k':
				state = 5
			case r == 'l':
				state = 26
			case r >= 'm' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 23:
			switch {
			case r >= '0' && r <= '9':
				state = 27
			case r == '[':
				state = 8
			default:
				return false
			}
		case 24:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 28
			case r >= '0' && r <= '9':
				state = 29
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 25:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 20
			case r >= '0' && r <= '9':
				state = 1
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 26:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'g':
				state = 5
			case r == 'h':
				state = 30
			case r >= 'i' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 27:
			switch {
			case r >= '0' && r <= '9':
				state = 31
			case r == '[':
				state = 8
			default:
				return false
			}
		case 28:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 32
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 29:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 28
			case r >= '0' && r <= '9':
				state = 33
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 30:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'n':
				state = 5
			case r == 'o':
				state = 34
			case r >= 'p' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 31:
			switch {
			case r == '[':
				state = 8
			default:
				return false
			}
		case 32:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 35
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 33:
			switch {
			case r == '-':
				state = 1
			case r == '.':
				state = 28
			case r >= '0' && r <= '9':
				state = 1
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 34:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'r':
				state = 5
			case r == 's':
				state = 36
			case r >= 't' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 35:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 37
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 36:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 's':
				state = 5
			case r == 't':
				state = 38
			case r >= 'u' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 37:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			case r == ':':
				state = 7
			case r == '[':
				state = 8
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 38:
			switch {
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 5
			case r == ':':
				state = 11
			case r >= 'A' && r <= 'Z':
				state = 4
			case r == '[':
				state = 8
			case r == '_':
				state = 5
			case r >= 'a' && r <= 'z':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 8
}
