// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^(((\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(([a-z0-9-_]+\.)+[a-z]{2,3})|(localhost)|(\w*::\w+)+)(:\d{1,5})?)$`

package matchers

// MatchHost reports whether input fully matches the regex `^(((\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(([a-z0-9-_]+\.)+[a-z]{2,3})|(localhost)|(\w*::\w+)+)(:\d{1,5})?)$`.
func MatchHost(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 2
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'k':
				state = 5
			case c == 'l':
				state = 6
			case c >= 'm' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 1:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 9
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 3:
			switch {
			case c == ':':
				state = 10
			default:
				return false
			}
		case 4:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 5:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'n':
				state = 5
			case c == 'o':
				state = 11
			case c >= 'p' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 8:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 13
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 9:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 14
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 10:
			switch {
			case c >= '0' && c <= '9':
				state = 15
			case c >= 'A' && c <= 'Z':
				state = 15
			case c == '_':
				state = 15
			case c >= 'a' && c <= 'z':
				state = 15
			default:
				return false
			}
		case 11:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'b':
				state = 5
			case c == 'c':
				state = 16
			case c >= 'd' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 12:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 17
			default:
				return false
			}
		case 13:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 19
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 14:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 15:
			switch {
			case c >= '0' && c <= '9':
				state = 15
			case c == ':':
				state = 20
			case c >= 'A' && c <= 'Z':
				state = 15
			case c == '_':
				state = 15
			case c >= 'a' && c <= 'z':
				state = 15
			default:
				return false
			}
		case 16:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c == 'a':
				state = 21
			case c >= 'b' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 17:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 23
			default:
				return false
			}
		case 18:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 24
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 19:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 25
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 20:
			switch {
			case c >= '0' && c <= '9':
				state = 26
			case c == ':':
				state = 10
			default:
				return false
			}
		case 21:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'k':
				state = 5
			case c == 'l':
				state = 27
			case c >= 'm' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 22:
			switch {
			case c >= '0' && c <= '9':
				state = 26
			default:
				return false
			}
		case 23:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 24:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 29
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 25:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 26:
			switch {
			case c >= '0' && c <= '9':
				state = 30
			default:
				return false
			}
		case 27:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'g':
				state = 5
			case c == 'h':
				state = 31
			case c >= 'i' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 28:
			switch {
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 32
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 29:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 33
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 30:
			switch {
			case c >= '0' && c <= '9':
				state = 34
			default:
				return false
			}
		case 31:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'n':
				state = 5
			case c == 'o':
				state = 35
			case c >= 'p' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 32:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 36
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 33:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 1
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 34:
			switch {
			case c >= '0' && c <= '9':
				state = 37
			default:
				return false
			}
		case 35:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'r':
				state = 5
			case c == 's':
				state = 38
			case c >= 't' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 36:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 39
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 37:
			switch {
			case c >= '0' && c <= '9':
				state = 40
			default:
				return false
			}
		case 38:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 3
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 's':
				state = 5
			case c == 't':
				state = 41
			case c >= 'u' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 39:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 1
			case c == ':':
				state = 22
			case c == '_':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 40:
			switch {
			default:
				return false
			}
		case 41:
			switch {
			case c == '-':
				state = 1
			case c == '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 5
			case c == ':':
				state = 20
			case c >= 'A' && c <= 'Z':
				state = 4
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
	}
	switch state {
	case 15, 17, 23, 26, 30, 32, 34, 36, 37, 39, 40, 41:
		return true
	default:
		return false
	}
}
