// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^([0-9a-f]{2}:){5}[0-9a-f]{2}$`

package matchers

// MatchMAC reports whether input fully matches the regex `^([0-9a-f]{2}:){5}[0-9a-f]{2}$`.
func MatchMAC(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			case c >= 'a' && c <= 'f':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case c >= '0' && c <= '9':
				state = 2
			case c >= 'a' && c <= 'f':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c == ':':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'f':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case c >= '0' && c <= '9':
				state = 5
			case c >= 'a' && c <= 'f':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case c == ':':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case c >= '0' && c <= '9':
				state = 7
			case c >= 'a' && c <= 'f':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case c >= '0' && c <= '9':
				state = 8
			case c >= 'a' && c <= 'f':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case c == ':':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case c >= '0' && c <= '9':
				state = 10
			case c >= 'a' && c <= 'f':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case c >= '0' && c <= '9':
				state = 11
			case c >= 'a' && c <= 'f':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case c == ':':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case c >= '0' && c <= '9':
				state = 13
			case c >= 'a' && c <= 'f':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case c >= '0' && c <= '9':
				state = 14
			case c >= 'a' && c <= 'f':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case c == ':':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case c >= '0' && c <= '9':
				state = 16
			case c >= 'a' && c <= 'f':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case c >= '0' && c <= '9':
				state = 17
			case c >= 'a' && c <= 'f':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 17
}
