// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[a-z0-9\-_\.\$=\+]+@([a-z0-9\-_\.]+)+(\.[a-z]+)+.*$`

package matchers

import "unicode/utf8"

// MatchMsgID reports whether input fully matches the regex `^[a-z0-9\-_\.\$=\+]+@([a-z0-9\-_\.]+)+(\.[a-z]+)+.*$`.
func MatchMsgID(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == '$':
				state = 1
			case r == '+':
				state = 1
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			case r == '=':
				state = 1
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r == '$':
				state = 1
			case r == '+':
				state = 1
			case r >= '-' && r <= '.':
				state = 1
			case r >= '0' && r <= '9':
				state = 1
			case r == '=':
				state = 1
			case r == '@':
				state = 2
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '-' && r <= '.':
				state = 3
			case r >= '0' && r <= '9':
				state = 3
			case r == '_':
				state = 3
			case r >= 'a' && r <= 'z':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == '-':
				state = 3
			case r == '.':
				state = 4
			case r >= '0' && r <= '9':
				state = 3
			case r == '_':
				state = 3
			case r >= 'a' && r <= 'z':
				state = 3
			default:
				return false
			}
		case 4:
			switch {
			case r == '-':
				state = 3
			case r == '.':
				state = 4
			case r >= '0' && r <= '9':
				state = 3
			case r == '_':
				state = 3
			case r >= 'a' && r <= 'z':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= ',':
				state = 6
			case r == '-':
				state = 7
			case r == '.':
				state = 8
			case r == '/':
				state = 6
			case r >= '0' && r <= '9':
				state = 7
			case r >= ':' && r <= '^':
				state = 6
			case r == '_':
				state = 7
			case r == '`':
				state = 6
			case r >= 'a' && r <= 'z':
				state = 5
			case r >= '{' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= ',':
				state = 6
			case r == '-':
				state = 7
			case r == '.':
				state = 8
			case r == '/':
				state = 6
			case r >= '0' && r <= '9':
				state = 7
			case r >= ':' && r <= '^':
				state = 6
			case r == '_':
				state = 7
			case r == '`':
				state = 6
			case r >= 'a' && r <= 'z':
				state = 7
			case r >= '{' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 6
			case r >= '\v' && r <= ',':
				state = 6
			case r == '-':
				state = 7
			case r == '.':
				state = 8
			case r == '/':
				state = 6
			case r >= '0' && r <= '9':
				state = 7
			case r >= ':' && r <= '^':
				state = 6
			case r == '_':
				state = 7
			case r == '`':
				state = 6
			case r >= 'a' && r <= 'z':
				state = 5
			case r >= '{' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 5, 6, 7, 8:
		return true
	default:
		return false
	}
}
