// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[+-]?\d+$`

package matchers

// MatchNum reports whether input fully matches the regex `^[+-]?\d+$`.
func MatchNum(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c == '+':
				state = 1
			case c == '-':
				state = 1
			case c >= '0' && c <= '9':
				state = 2
			default:
				return false
			}
		case 1:
			switch {
			case c >= '0' && c <= '9':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 2
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 2
}
