// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^sig(hup|int|quit|ill|abrt|fpe|kill|segv|pipe|alrm|term|usr1|usr2|chld|cont|stop|tstp|tin|tout|bus|poll|prof|sys|trap|urg|vtalrm|xcpu|xfsz|iot|emt|stkflt|io|cld|pwr|info|lost|winch|unused).*$`

package matchers

import "unicode/utf8"

// MatchSig reports whether input fully matches the regex `^sig(hup|int|quit|ill|abrt|fpe|kill|segv|pipe|alrm|term|usr1|usr2|chld|cont|stop|tstp|tin|tout|bus|poll|prof|sys|trap|urg|vtalrm|xcpu|xfsz|iot|emt|stkflt|io|cld|pwr|info|lost|winch|unused).*$`.
func MatchSig(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r == 's':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r == 'i':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r == 'g':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case r == 'a':
				state = 4
			case r == 'b':
				state = 5
			case r == 'c':
				state = 6
			case r == 'e':
				state = 7
			case r == 'f':
				state = 8
			case r == 'h':
				state = 9
			case r == 'i':
				state = 10
			case r == 'k':
				state = 11
			case r == 'l':
				state = 12
			case r == 'p':
				state = 13
			case r == 'q':
				state = 14
			case r == 's':
				state = 15
			case r == 't':
				state = 16
			case r == 'u':
				state = 17
			case r == 'v':
				state = 18
			case r == 'w':
				state = 19
			case r == 'x':
				state = 20
			default:
				return false
			}
		case 4:
			switch {
			case r == 'b':
				state = 21
			case r == 'l':
				state = 22
			default:
				return false
			}
		case 5:
			switch {
			case r == 'u':
				state = 23
			default:
				return false
			}
		case 6:
			switch {
			case r == 'h':
				state = 24
			case r == 'l':
				state = 25
			case r == 'o':
				state = 26
			default:
				return false
			}
		case 7:
			switch {
			case r == 'm':
				state = 27
			default:
				return false
			}
		case 8:
			switch {
			case r == 'p':
				state = 28
			default:
				return false
			}
		case 9:
			switch {
			case r == 'u':
				state = 29
			default:
				return false
			}
		case 10:
			switch {
			case r == 'l':
				state = 30
			case r == 'n':
				state = 31
			case r == 'o':
				state = 32
			default:
				return false
			}
		case 11:
			switch {
			case r == 'i':
				state = 33
			default:
				return false
			}
		case 12:
			switch {
			case r == 'o':
				state = 34
			default:
				return false
			}
		case 13:
			switch {
			case r == 'i':
				state = 35
			case r == 'o':
				state = 36
			case r == 'r':
				state = 37
			case r == 'w':
				state = 38
			default:
				return false
			}
		case 14:
			switch {
			case r == 'u':
				state = 39
			default:
				return false
			}
		case 15:
			switch {
			case r == 'e':
				state = 40
			case r == 't':
				state = 41
			case r == 'y':
				state = 42
			default:
				return false
			}
		case 16:
			switch {
			case r == 'e':
				state = 43
			case r == 'i':
				state = 44
			case r == 'o':
				state = 45
			case r == 'r':
				state = 46
			case r == 's':
				state = 47
			default:
				return false
			}
		case 17:
			switch {
			case r == 'n':
				state = 48
			case r == 'r':
				state = 49
			case r == 's':
				state = 50
			default:
				return false
			}
		case 18:
			switch {
			case r == 't':
				state = 51
			default:
				return false
			}
		case 19:
			switch {
			case r == 'i':
				state = 52
			default:
				return false
			}
		case 20:
			switch {
			case r == 'c':
				state = 53
			case r == 'f':
				state = 54
			default:
				return false
			}
		case 21:
			switch {
			case r == 'r':
				state = 55
			default:
				return false
			}
		case 22:
			switch {
			case r == 'r':
				state = 56
			default:
				return false
			}
		case 23:
			switch {
			case r == 's':
				state = 57
			default:
				return false
			}
		case 24:
			switch {
			case r == 'l':
				state = 58
			default:
				return false
			}
		case 25:
			switch {
			case r == 'd':
				state = 57
			default:
				return false
			}
		case 26:
			switch {
			case r == 'n':
				state = 59
			default:
				return false
			}
		case 27:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 28:
			switch {
			case r == 'e':
				state = 57
			default:
				return false
			}
		case 29:
			switch {
			case r == 'p':
				state = 57
			default:
				return false
			}
		case 30:
			switch {
			case r == 'l':
				state = 57
			default:
				return false
			}
		case 31:
			switch {
			case r == 'f':
				state = 60
			case r == 't':
				state = 57
			default:
				return false
			}
		case 32:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 61
			case r >= '\v' && r <= 's':
				state = 61
			case r == 't':
				state = 57
			case r >= 'u' && r <= '\U0010ffff':
				state = 61
			default:
				return false
			}
		case 33:
			switch {
			case r == 'l':
				state = 62
			default:
				return false
			}
		case 34:
			switch {
			case r == 's':
				state = 63
			default:
				return false
			}
		case 35:
			switch {
			case r == 'p':
				state = 64
			default:
				return false
			}
		case 36:
			switch {
			case r == 'l':
				state = 65
			default:
				return false
			}
		case 37:
			switch {
			case r == 'o':
				state = 66
			default:
				return false
			}
		case 38:
			switch {
			case r == 'r':
				state = 57
			default:
				return false
			}
		case 39:
			switch {
			case r == 'i':
				state = 67
			default:
				return false
			}
		case 40:
			switch {
			case r == 'g':
				state = 68
			default:
				return false
			}
		case 41:
			switch {
			case r == 'k':
				state = 69
			case r == 'o':
				state = 70
			default:
				return false
			}
		case 42:
			switch {
			case r == 's':
				state = 57
			default:
				return false
			}
		case 43:
			switch {
			case r == 'r':
				state = 71
			default:
				return false
			}
		case 44:
			switch {
			case r == 'n':
				state = 57
			default:
				return false
			}
		case 45:
			switch {
			case r == 'u':
				state = 72
			default:
				return false
			}
		case 46:
			switch {
			case r == 'a':
				state = 73
			default:
				return false
			}
		case 47:
			switch {
			case r == 't':
				state = 74
			default:
				return false
			}
		case 48:
			switch {
			case r == 'u':
				state = 75
			default:
				return false
			}
		case 49:
			switch {
			case r == 'g':
				state = 57
			default:
				return false
			}
		case 50:
			switch {
			case r == 'r':
				state = 76
			default:
				return false
			}
		case 51:
			switch {
			case r == 'a':
				state = 77
			default:
				return false
			}
		case 52:
			switch {
			case r == 'n':
				state = 78
			default:
				return false
			}
		case 53:
			switch {
			case r == 'p':
				state = 79
			default:
				return false
			}
		case 54:
			switch {
			case r == 's':
				state = 80
			default:
				return false
			}
		case 55:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 56:
			switch {
			case r == 'm':
				state = 57
			default:
				return false
			}
		case 57:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 61
			case r >= '\v' && r <= '\U0010ffff':
				state = 61
			default:
				return false
			}
		case 58:
			switch {
			case r == 'd':
				state = 57
			default:
				return false
			}
		case 59:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 60:
			switch {
			case r == 'o':
				state = 57
			default:
				return false
			}
		case 61:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 61
			case r >= '\v' && r <= '\U0010ffff':
				state = 61
			default:
				return false
			}
		case 62:
			switch {
			case r == 'l':
				state = 57
			default:
				return false
			}
		case 63:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 64:
			switch {
			case r == 'e':
				state = 57
			default:
				return false
			}
		case 65:
			switch {
			case r == 'l':
				state = 57
			default:
				return false
			}
		case 66:
			switch {
			case r == 'f':
				state = 57
			default:
				return false
			}
		case 67:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 68:
			switch {
			case r == 'v':
				state = 57
			default:
				return false
			}
		case 69:
			switch {
			case r == 'f':
				state = 81
			default:
				return false
			}
		case 70:
			switch {
			case r == 'p':
				state = 57
			default:
				return false
			}
		case 71:
			switch {
			case r == 'm':
				state = 57
			default:
				return false
			}
		case 72:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 73:
			switch {
			case r == 'p':
				state = 57
			default:
				return false
			}
		case 74:
			switch {
			case r == 'p':
				state = 57
			default:
				return false
			}
		case 75:
			switch {
			case r == 's':
				state = 82
			default:
				return false
			}
		case 76:
			switch {
			case r >= '1' && r <= '2':
				state = 57
			default:
				return false
			}
		case 77:
			switch {
			case r == 'l':
				state = 83
			default:
				return false
			}
		case 78:
			switch {
			case r == 'c':
				state = 84
			default:
				return false
			}
		case 79:
			switch {
			case r == 'u':
				state = 57
			default:
				return false
			}
		case 80:
			switch {
			case r == 'z':
				state = 57
			default:
				return false
			}
		case 81:
			switch {
			case r == 'l':
				state = 85
			default:
				return false
			}
		case 82:
			switch {
			case r == 'e':
				state = 86
			default:
				return false
			}
		case 83:
			switch {
			case r == 'r':
				state = 87
			default:
				return false
			}
		case 84:
			switch {
			case r == 'h':
				state = 57
			default:
				return false
			}
		case 85:
			switch {
			case r == 't':
				state = 57
			default:
				return false
			}
		case 86:
			switch {
			case r == 'd':
				state = 57
			default:
				return false
			}
		case 87:
			switch {
			case r == 'm':
				state = 57
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 32, 57, 61:
		return true
	default:
		return false
	}
}
