// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\d+(\.\d+)?[kmgt]i?b?(ytes?)?.*$`

package matchers

import "unicode/utf8"

// MatchSize reports whether input fully matches the regex `^\d+(\.\d+)?[kmgt]i?b?(ytes?)?.*$`.
func MatchSize(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r == '.':
				state = 2
			case r >= '0' && r <= '9':
				state = 1
			case r == 'g':
				state = 3
			case r == 'k':
				state = 3
			case r == 'm':
				state = 3
			case r == 't':
				state = 3
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= 'a':
				state = 5
			case r == 'b':
				state = 6
			case r >= 'c' && r <= 'h':
				state = 5
			case r == 'i':
				state = 7
			case r >= 'j' && r <= 'x':
				state = 5
			case r == 'y':
				state = 8
			case r >= 'z' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 4:
			switch {
			case r >= '0' && r <= '9':
				state = 4
			case r == 'g':
				state = 3
			case r == 'k':
				state = 3
			case r == 'm':
				state = 3
			case r == 't':
				state = 3
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= 'x':
				state = 5
			case r == 'y':
				state = 8
			case r >= 'z' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= 'a':
				state = 5
			case r == 'b':
				state = 6
			case r >= 'c' && r <= 'x':
				state = 5
			case r == 'y':
				state = 8
			case r >= 'z' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= 's':
				state = 5
			case r == 't':
				state = 9
			case r >= 'u' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= 'd':
				state = 5
			case r == 'e':
				state = 10
			case r >= 'f' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= 'r':
				state = 5
			case r == 's':
				state = 11
			case r >= 't' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 3, 5, 6, 7, 8, 9, 10, 11:
		return true
	default:
		return false
	}
}
