// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^.*\d{1,2}:\d{1,2}(:\d{1,2})?.*$`

package matchers

import "unicode/utf8"

// MatchTime reports whether input fully matches the regex `^.*\d{1,2}:\d{1,2}(:\d{1,2})?.*$`.
func MatchTime(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 2
			case r >= ':' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 2
			case r >= ':' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 2
			case r == ':':
				state = 3
			case r >= ';' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 1
			case r >= '\v' && r <= '/':
				state = 1
			case r >= '0' && r <= '9':
				state = 4
			case r >= ':' && r <= '\U0010ffff':
				state = 1
			default:
				return false
			}
		case 4:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 6
			case r == ':':
				state = 7
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 8
			case r >= ':' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 8
			case r == ':':
				state = 7
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 7:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 9
			case r >= ':' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 8:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 8
			case r == ':':
				state = 10
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 9:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 11
			case r == ':':
				state = 7
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 10:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 4
			case r >= ':' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		case 11:
			switch {
			case r >= '\x00' && r <= '\t':
				state = 5
			case r >= '\v' && r <= '/':
				state = 5
			case r >= '0' && r <= '9':
				state = 8
			case r == ':':
				state = 7
			case r >= ';' && r <= '\U0010ffff':
				state = 5
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	switch state {
	case 4, 5, 6, 7, 8, 9, 10, 11:
		return true
	default:
		return false
	}
}
