// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^\w{2,}://(\S+/?)+$`

package matchers

import "unicode/utf8"

// MatchURI reports whether input fully matches the regex `^\w{2,}://(\S+/?)+$`.
func MatchURI(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return false
		}
		switch state {
		case 0:
			switch {
			case r >= '0' && r <= '9':
				state = 1
			case r >= 'A' && r <= 'Z':
				state = 1
			case r == '_':
				state = 1
			case r >= 'a' && r <= 'z':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			case r >= 'A' && r <= 'Z':
				state = 2
			case r == '_':
				state = 2
			case r >= 'a' && r <= 'z':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case r >= '0' && r <= '9':
				state = 2
			case r == ':':
				state = 3
			case r >= 'A' && r <= 'Z':
				state = 2
			case r == '_':
				state = 2
			case r >= 'a' && r <= 'z':
				state = 2
			default:
				return false
			}
		case 3:
			switch {
			case r == '/':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case r == '/':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 6
			case r == '\v':
				state = 6
			case r >= '\x0e' && r <= '\x1f':
				state = 6
			case r >= '!' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case r >= '\x00' && r <= '\b':
				state = 6
			case r == '\v':
				state = 6
			case r >= '\x0e' && r <= '\x1f':
				state = 6
			case r >= '!' && r <= '.':
				state = 6
			case r == '/':
				state = 6
			case r >= '0' && r <= '\U0010ffff':
				state = 6
			default:
				return false
			}
		default:
			return false
		}
		i += size
	}
	return state == 6
}
