// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^v?(\d+\.){1}((\d|[a-z])+\.)*(\d|[a-z])+$`

package matchers

// MatchVer reports whether input fully matches the regex `^v?(\d+\.){1}((\d|[a-z])+\.)*(\d|[a-z])+$`.
func MatchVer(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {
		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			case c == 'v':
				state = 2
			default:
				return false
			}
		case 1:
			switch {
			case c == '.':
				state = 3
			case c >= '0' && c <= '9':
				state = 1
			default:
				return false
			}
		case 2:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			default:
				return false
			}
		case 3:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case c == '.':
				state = 5
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 5:
			switch {
			case c >= '0' && c <= '9':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		default:
			return false
		}
	}
	return state == 4
}
